### ISSUE TITLE
Revert specific exercise

### ISSUE THREAD

**Issue by lowks** [exercism/exercism.io#1424] opened 2014-02-24 02:43 UTC
It would be supremely great if the cli tool that comes with exercism can do this: 

`exercism revert beer.clj` which reverts back to the last submitted exercise as a parachute if you are up the creek without a paddle. Okay, my metaphors are messed up, but I am sure you know what I mean.

**Comment by kytrinyx** [comment] 2015-03-26 15:28
I am going to close this as a duplicate of #1385. Since solutions can now be multiple files, I think it makes sense to revert a problem by name rather than by specifying a specific file.

**Closed by kytrinyx** 2015-03-26 15:28 UTC
Labels: code
