### ISSUE TITLE
Completing a track shows lorem ipsum

### ISSUE THREAD

**Issue by macta** [exercism/exercism.io#4176] opened 2018-08-06 06:41 UTC
Came across this by chance as our track has only 1 exercise - completing it shows:

Well Done!
You've completed the Pharo Track
lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum.

I'm guess this is some text that was intended to be written up? Or is this something track specific that you have to implement?

**Comment by jackhughesweb** [comment] 2018-08-06 09:05
Duplicate of #3839

**Closed** 2018-08-06 11:16 UTC
