### ISSUE TITLE
Old notifications (would be great)

### ISSUE THREAD

**Issue by vaughankg** [exercism/exercism.io#2183] opened 2015-01-30 18:32 UTC
A couple of times now I have looked at my [notifications](http://exercism.io/notifications), skim read them with the intention of coming back but when I do return they are nowhere to be found. 

Can we keep a paginated list of old notifications similar to the one in [recently viewed](http://exercism.io/looks) submissions?

**Comment by kytrinyx** [comment] 2015-01-31 03:24
We don't, unfortunately. We have a sweeper task that clears out old notifications daily.

That said, I'm looking to replace notifications with an activity stream: https://github.com/exercism/exercism.io/issues/1899

I think this will work much, much better for exercism.

**Comment by kytrinyx** [comment] 2015-01-31 03:47
I'm going to close this as a duplicate of #1899 -- if you want to elaborate on this in any way, I'd love to hear your thoughts over in that issue.

Thanks!

**Closed by kytrinyx** 2015-01-31 03:47 UTC
Labels: duplicate
