### ISSUE TITLE
Currently getting 503 error for "Profile" under user pull down.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#3181] opened 2016-10-17 08:19 UTC
When I click on "kotp" (my username top right of page) and select "Profile" from that pull down, I get this response in the web browser.

![screenshot from 2016-10-17 04-16-04](https://cloud.githubusercontent.com/assets/16747/19430055/b92ff37c-9420-11e6-9869-34e766ed31c0.png)

**Comment by kotp** [comment] 2016-10-17 08:30
@nobbz confirms that it is happening for your own profile, but not for others.

**Comment by NobbZ** [comment] 2016-10-17 09:28
Right now it seems as if @kotp and my profile are randomly loading now but take quite a while to do so.

@kotp as a reviewcound of ~2.7k in a single language, and I do have a reviewcount of ~2k over a couple of languages. I then tried @[etrepum](http://exercism.io/etrepum) who I do remember as quite active reviewer in the functional language tracks. He times out as well for me.

**Comment by NobbZ** [comment] 2016-10-17 10:47
Some further testing brought the following result when each site was reachable:

| User | Reviews | response time |
|---|---:|---:|
| NobbZ | ~2k | ~3 sec |
| kotp | ~2.7k | ~3 sec |
| kytrinyx | ~6.8k | ~9 sec |
| etrepum | ~7.7k | ~12 sec |

So even if there is a huge spike between kytrinyx and etrepum in response time, there seems to be some correlation between response/processing time and review count.

I have to admit though, that I had networking trouble while trying to measure etrepum, so this could have influenced the samples (dropping packets and even completely loosing connection).

**Comment by jtigger** [comment] 2016-10-17 19:56
The same symptom was reported by @cds-admal, today, on a different page.

> *2016-10-17 @ 06:48 PT*
> **cds-amal:** Hi, I'm getting a "Error 503 first byte timeout" when I try to view the activity stream. This has been going on for a 5 days or so
> ```
Error 503 first byte timeout
first byte timeout
Guru Mediation:
Details: cache-jfk8141-JFK 1476715665 1819433167
Varnish cache server
```

**Comment by jtigger** [comment] 2016-10-17 20:00
Note this guide: https://docs.fastly.com/guides/debugging/common-503-errors

**Comment by bernardoamc** [comment] 2016-10-18 03:04
We can probably improve the queries performed to build the Profile (even if that's not the main cause), going to take a look at it this week.

**Comment by jtigger** [comment] 2016-10-18 13:39
Here's a sample of the first two from the sequence of requests on the Activity Stream page:

First is the 302 (included to establish the start time of the request (I trimmed headers that appear to be irrelevant to this discussion):
```
Request URL:http://exercism.io/inbox
Request Method:GET
Status Code:302 Found
Remote Address:151.101.128.204:80
Location: http://exercism.io/tracks/clojure/exercises
Date: Tue, 18 Oct 2016 04:46:39 GMT
```

After some delay (here, 30 seconds), the actual page times-out:

```
Request URL:http://exercism.io/tracks/clojure/exercises
Request Method:GET
Status Code:503 first byte timeout
Remote Address:151.101.128.204:80
Response Headers
view parsed
HTTP/1.1 503 first byte timeout
Server: Varnish
Content-Type: text/html; charset=utf-8
Content-Length: 448
Accept-Ranges: bytes
Date: Tue, 18 Oct 2016 04:47:09 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-jfk8123-JFK
X-Cache: MISS
X-Cache-Hits: 0
Request Headers
view parsed
GET /tracks/clojure/exercises HTTP/1.1
Host: exercism.io
User-Agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
```

**Comment by jtigger** [comment] 2016-10-18 13:59
@bernardoamc said, above:
> We can probably improve the queries performed to build the Profile (even if that's not the main cause), going to take a look at it this week.

In fact, I believe this is the heart of the problem.  The CDN is timing out (30 seconds) if the origin server does not respond.

This appears to be happening in two places:

1. User profiles (when that target user has a significant number of reviews, >2k).
- Activity Stream (for users who have participated in a number of tracks).

Some tuning can help in the short term.  We can squeeze on that end of the tube for a while, but I believe we're bumping up against some scaling challenges.

**Comment by bernardoamc** [comment] 2016-10-20 02:38
> Some tuning can help in the short term. We can squeeze on that end of the tube for a while, but I believe we're bumping up against some scaling challenges.

@jtigger That's probably true! Going to work on the code in the next days, but it's always a good idea to have a backup plan in case the problem is not solved.

**Comment by bernardoamc** [comment] 2016-10-23 20:45
I will close this issue, thanks for bringing this up everyone! :)

**Closed** 2016-10-23 20:45 UTC

**Comment by Insti** [comment] 2016-10-23 21:07
Thanks for fixing it @bernardoamc :heart: :tada:

**Comment by jtigger** [comment] 2016-10-24 14:49
There was a separate complaint about the Activity Stream in the support chat.  If I've properly followed-up, I'll report back that this user's experience is better or I created a separate issues for that page.

If it's been more than a week since this comment and no additional movement, please poke me.

**Comment by bernardoamc** [comment] 2016-10-24 17:32
Oh, I missed the part about the activity stream, going to take a look at it and see if we can improve the response time. :)

**Comment by jtigger** [comment] 2016-10-25 13:12
Solid, @bernardoamc.  Per @cds-amal, your work improve the performance of that page too, but it's still a bit slow for some and it sounds like it has some side-effects.  I created a separate issue for that: #3206.
