### ISSUE TITLE
Error when accepting invitation

### ISSUE THREAD

**Issue by catherinedevlin** [exercism/exercism.io#3455] opened 2017-04-07 19:34 UTC
I've been getting "Sorry!  That's our fault!" errors for several days when trying to accept an invitation to the 18f team: http://exercism.io/teams/18f/invitation/accept

The onlly thing I know that might have caused an unusual case is that my teammates made me a *manager* of the team before I was a member.  Then they sent me an invite, but maybe it's impossible to accept an invite when you've been made a manager?  I hoped to fix it by removing myself as manager, but I'm still getting the error.

**Comment by kotp** [comment] 2017-04-08 07:51
Something seems to be happening that may be related, but I invited someone last week, and apparently they have accepted (they are in the members listing) but it is still in the invite area... and when I removed the person, they were removed also from the 'active' list.

**Comment by kotp** [comment] 2017-04-08 07:55
Ah, in the graphic, the confusion comes because once accepted they are directly below the blue "invite".  Unless there are current invited members, this is not clear that this is not the active list of invited members... once all are included, the "Invited members" heading disappears... leaving just the "invite" wording.. making it appear that they are still in the invite queue.  The page that this appears on is the [manage page](http://exercism.io/teams/aavalam/manage)
![selection_003](https://cloud.githubusercontent.com/assets/16747/24826912/d845b87a-1c0e-11e7-8c24-42ad61c63921.png)

**Comment by kytrinyx** [comment] 2017-04-10 15:45
So sorry you're running into this. You should be able to be a manager and then get invited, those are supposed to be independent of each other. Let me dig into this in the next few days to see what's going on!

**Comment by kytrinyx** [comment] 2017-04-19 16:13
You've already been confirmed as a member, but for some reason your invitation persisted, so when you tried accepting it, it crashed because it was trying to create a duplicate record.

I've tried figuring out why the invitation persisted—the way the code is written that shouldn't happen (except I'm probably missing something).

I'm going to go ahead and close this, as I haven't found reproduction steps. If it happens again, then we're going to need to spend more time trying to reproduce the error so we can get to the bottom of this!

**Comment by iHiD** [comment] 2017-04-19 16:35
@kytrinyx 

At a glance, might this series of things cause it?

```
team.invite([new_user], team_owner)
team.managed_by(new_user)
```

Where the second is called [here](https://github.com/exercism/exercism.io/blob/cf8bf31cbfdda3fa04d4db1105e245226910f351/app/routes/teams.rb#L280):

**Comment by kytrinyx** [comment] 2017-04-19 16:41
Not that I know of. Managing a team doesn't create a membership record. When you accept an invitation, though, there's a transaction where the membership record is created and the invitation is destroyed.

**Comment by iHiD** [comment] 2017-04-19 18:19
Yeah. Sorry. You're totally right.

**Comment by c1505** [comment] 2017-04-19 20:26
Having the same issue.  A member was invited to join the team and got an error when trying to.  I tried deleting the invite and had him request to join to see if that might fix it.  Now when I try to accept the join request, I get an error. 

Other members have been able to join the team as recently as yesterday.

![image](https://cloud.githubusercontent.com/assets/6599077/25200471/6df30e66-251c-11e7-8042-430b4fd9fc6b.png)

After clicking accept ->
![image](https://cloud.githubusercontent.com/assets/6599077/25200545/b170b364-251c-11e7-84e9-933652a6170d.png)

**Comment by bernardoamc** [comment] 2017-04-19 20:28
Thanks for reporting @catherinedevlin and @c1505, I will take a look at this tonight and see if I can find what could possibly be causing this. :)

**Comment by allcentury** [comment] 2017-04-19 20:29
Can you share the bugsnag report @kytrinyx ?  That would be a good place to start.

**Comment by kytrinyx** [comment] 2017-04-19 21:28
@allcentury I couldn't find anything in Bugsnag (which suggests that something changed with the settings or setup there).

@c1505 do you know what the sequence of events was for this to happen? I'd love to try to reproduce this locally.

**Comment by bernardoamc** [comment] 2017-04-20 01:53
> You've already been confirmed as a member, but for some reason your invitation persisted, so when you tried accepting it, it crashed because it was trying to create a duplicate record.

@kytrinyx We might want to change [this](https://github.com/exercism/exercism.io/blob/master/lib/exercism/team_membership_invite.rb#L19) to `destroy!` so we can rollback the membership in case we fail to destroy the invite. This solves just part of the problem though... 

If we are getting an error right now it should be `TeamMembership.create!` fault, since `destroy` is not raising anything. What could possibly make this fail? A previous membership? 🤔

**Comment by kytrinyx** [comment] 2017-04-20 03:01
Oooh, yepp. We should definitely make that `destroy!`.

I wonder what would happen if we added the same person twice in the same list.

[... later... ] Uh, yeah. That might actually be it. Let me test this locally.

**Comment by kytrinyx** [comment] 2017-04-20 03:04
Nope. That's not it. I tried both adding the same user twice in the same action, and also adding the same user twice in different actions. Both worked just fine.

**Comment by bernardoamc** [comment] 2017-04-20 04:09
> Nope. That's not it. I tried both adding the same user twice in the same action, and also adding the same user twice in different actions. Both worked just fine.

Too bad... I also couldn't reproduce, back to the whiteboard.

**Comment by kytrinyx** [comment] 2017-04-21 03:42
@bernardoamc I think you're right that this happened because a `destroy` failed, but didn't raise the exception so the transaction didn't roll back.

**Comment by bernardoamc** [comment] 2017-04-21 05:01
> @bernardoamc I think you're right that this happened because a destroy failed, but didn't raise the exception so the transaction didn't roll back.

@kytrinyx Yeah, I feel that's the reason, but I can't reproduce! It's a good idea to fix the `destroy` nonetheless. :)

**Comment by c1505** [comment] 2017-04-22 14:38
@kytrinyx I sent the initial invite a while ago(guessing a few months) and I don't recall doing anything differently with the invite than with other ones I sent.

**Comment by kytrinyx** [comment] 2017-05-05 15:46
I've opened a PR to fix the thing we did find. That PR will close this, and if it comes up again we'll see if we can find reproduction steps.

Thanks!

**Closed** 2017-05-05 17:17 UTC
Labels: bug
