### ISSUE TITLE
Use descriptive alt tag for profile image

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3923] opened 2018-06-23 11:02 UTC
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/161._
_Originally posted by @ErikSchierboom._

#

The alt tag for the user's image icon is now the user's ID. It is probably better to replace this with the user's account name.

**Comment by iHiD** [comment] 2018-07-24 08:49
Duplicate of https://github.com/exercism/exercism.io/issues/3968

**Closed** 2018-07-24 08:49 UTC
Labels: imported-from/v2-feedback
