### ISSUE TITLE
Syntax highlighting for ruby has a problem for certain syntax sturctures

### ISSUE THREAD

**Issue by yilkalargaw** [exercism/exercism.io#3672] opened 2017-11-24 12:53 UTC

**Comment by NobbZ** [comment] 2017-11-24 12:55
Which ones? Can you provide an example?

And since we will swap the highlighter anyway with exercism [v2](https://v2.exercism.io/), does the problem exist there as well?

**Comment by yilkalargaw** [comment] 2017-11-24 13:08
in ruby the code I submitted is at the following link "http://exercism.io/submissions/ce4ea1be1fb4469991ff937ad0937964"

the code is the one below and it starts with the 
 `class Sieve

        #constructor
        def initialize(n)
            @num = n
        end

        #the function
        def primes
            range=Array.new()
            non_prime=Array.new()
            
            (2..@num).each do |t| # an array of the number range 2-number given
                range<<t
#starting from here is marked in pink while the code is still valid  
          end
            
            
            (2..@num/2).each do |x|   #since there could not be any factor greater than n/2
                if non_prime.include?(x)
                    next
                else
                    (2..@num).each do |nb|
                        if non_prime.include?(nb)==false and nb!=x and nb%x==0
                            non_prime<<nb
                        else
                            next
                        end
                    end
                end
            end
            
            return range-non_prime
        end
end


 module BookKeeping
     VERSION = 1 # Where the version number matches the one in the test.
 end`

**Comment by NobbZ** [comment] 2017-11-24 13:27
Yeah, the Highlighter does think `<<t` were starting a heredoc and wants a sole `t` on a line to end it.

If you insert spaces around the `<<` it should be highlighted properly, also its easier to read for humans as well then (at least thats my opinion, I like operators surrounded by space).

Also I'm still interested if the problem persists in v2.

**Comment by NobbZ** [comment] 2017-11-24 13:33
Since this bug also exists in the current version, I created a bug upstream.

**Comment by yilkalargaw** [comment] 2017-11-24 13:36
thanks the spaces worked and the problem also persists in exercism v2

**Comment by NobbZ** [comment] 2017-11-24 13:48
v2 uses prism.js as a highlighter, I can't find a playground to set up an example quickly to report a bug.

Perhaps someone else can do this then?

**Comment by yilkalargaw** [comment] 2017-11-24 15:09
sorry but I was wrong prism.js works fine with the above code syntax I think it would work fine on Exercismv2. I tested the wrong branch . For prism js play ground use [http://prismjs.com/test.html]

**Comment by kytrinyx** [comment] 2017-12-22 17:40
@yilkalargaw excellent, thanks for confirming that.

**Comment by Insti** [comment] 2018-01-26 14:20
Closing this issue:

* Upstream (Rouge) issue has been raised.
* Exercism V1 will not be updated to fix this.
* Exercism V2 does not have this issue.
 
Thanks for the report and the research into  the cause :heart:

**Closed by Insti** 2018-01-26 14:20 UTC
