### ISSUE TITLE
default text for language doc topics is missing

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#3356] opened 2017-01-23 10:18 UTC
According to https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/x/docs/track.rb#L25, if a track has no (e.g.) LEARNING.md file, instead the default https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/x/docs/md/track/LEARNING.md should get included.

This is currently not the case - see how http://exercism.io/languages/nasm/learning is blank, where https://github.com/exercism/xnasm has no docs/LEARNING.md file.

It should be the case that the default LEARNING.md file gets included.

This appears to be similar to #3351 (already fixed) and #3355 (not yet fixed). Someone attempting to fix this might consider using a similar fix as the fix to #3351, and also see whether the same fix can be applied to #3355 as well.

**Comment by petertseng** [comment] 2017-01-23 10:18
I am sorry, I meant http://exercism.io/languages/nasm/learning - edited.

**Comment by rohangokhale** [comment] 2017-02-26 23:35
I think this might be due to the line 
File.read("./x/docs/md/track/#{topic.upcase}.md")
in the read function in track.rb. There is a '#' symbol there that doesn't appear to be part of the directory structure. I'm brand new to this project, so apologies if this isn't the cause of the issue.

**Comment by kytrinyx** [comment] 2017-02-27 18:03
@rohangokhale Thanks! The `#{...}` syntax is string interpolation in Ruby, so I don't think that's what is going on.

**Comment by nholden** [comment] 2017-04-04 02:53
I did some initial investigation into this bug, and it looks like we no longer use [`X::Docs::Track`](https://github.com/exercism/exercism.io/blob/master/x/docs/track.rb), so we never hit the logic to use the default `LEARNING.md` file. Instead, [the `Languages` router grabs `docs` from `Trackler`](https://github.com/exercism/exercism.io/blob/master/app/routes/languages.rb#L44-L51). 

[Here's the method](https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb#L151-L161) in `Trackler` that grabs the contents of a file to return when the `Languages` router calls [`Trackler::Track#docs`](https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb#L84-L86). [`Trackler::Track#document_contents`](https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb#L151-L161) doesn't have any logic to fallback to default content. Instead, it returns an empty string if it doesn't find a matching file.

So I think we have two options here:

1. Move the default text to `Trackler` and update `Trackler::Track` to use the default text when a file isn't found.
2. Write a new wrapper in `exercism.io` for a `Trackler::Track` (or just the `OpenStruct` returned by `Trackler::Track#docs`) that will use the default text in this repo when it gets an empty string from `Trackler`.

I'm leaning toward option 2 because the default text seems specific to exercism.io, but I'm not sure I have all the context to make that call. [Here's the commit from October](https://github.com/exercism/exercism.io/commit/ac660a4836682150dfec6f3c862a2dc6ccdab868) that replaced the wrapper with the default text fallback logic with `Trackler`.

If anyone has thoughts or additional context, please chime in! Otherwise, I'll continue to plug away at this one.

**Comment by kytrinyx** [comment] 2017-04-17 23:08
Fixed in #3454 :tada: deploying in a sec.

**Closed by kytrinyx** 2017-04-17 23:08 UTC
Labels: bug
