### ISSUE TITLE
moving legacy solution to a mentors queue causes re-ordering of the track

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3833] opened 2018-07-14 21:05 UTC
`hello-world` should be the first exercise, and was before I requested mentoring.

![out-of-order](https://user-images.githubusercontent.com/58951/42728428-5308631a-87ba-11e8-8c33-03b7cc998731.png)

If needed, this screenshot was taken from typescript.

**Comment by NobbZ** [comment] 2018-07-15 22:34
I'm not disliking it, it's just not as expected, as I expected the order to comply with whatever is in the tracks config.

**Comment by nickborromeo** [comment] 2018-07-30 00:21
Given that this was a decision that was made is "feature not a bug" 😃 can we go ahead and close this? Maybe we can add a doc about this so that if people are confused by this there is a source that we can point them to?

**Comment by iHiD** [comment] 2018-07-30 08:13
Good shout. I think only exercism-pros would really know this so I'm not going to worry about adding an FAQ but I'll happily look at a PR if anyone wants to.

**Closed** 2018-07-30 08:12 UTC
