### ISSUE TITLE
Bios duplicated on team pages

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/exercism.io#3874] opened 2018-07-16 22:19 UTC
e.g. at https://exercism.io/team/mentors and https://exercism.io/team/maintainers

<img width="1280" alt="screen shot 2018-07-16 at 23 16 35" src="https://user-images.githubusercontent.com/5421823/42786545-9b6ccf8e-894e-11e8-8165-80a78b4af0a4.png">
<img width="1280" alt="screen shot 2018-07-16 at 23 16 44" src="https://user-images.githubusercontent.com/5421823/42786546-9dd985a0-894e-11e8-9fb0-b922ba6f9d08.png">
<img width="1280" alt="screen shot 2018-07-16 at 23 16 58" src="https://user-images.githubusercontent.com/5421823/42786548-9f16bb68-894e-11e8-8920-cd746b3f42b5.png">

**Comment by iHiD** [comment] 2018-07-16 23:55
Duplicate of #3852

**Closed by iHiD** 2018-07-16 23:55 UTC
