### ISSUE TITLE
Running tests individually returns errors

### ISSUE THREAD

**Issue by kntsoriano** [exercism/exercism.io#3558] opened 2017-06-12 07:48 UTC
# Background
While reading through the [Setting up Local Development#Testing](https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md#testing), I stumbled upon this snippet in the document:

```
To run a single Ruby test, you can do so with:

`ruby path/to/the_test.rb`

If it complains about dependencies, then either we forgot to require the
correct dependencies (a distinct possibility), or we are depending on a particular
tag of a gem installed directly from GitHub (this happens on occasion).
```

To try and put issues like those to rest, I decided to write this script which loops through all the tests and runs them individually:

```
for f in $(find test/ -name '*_test.rb') do
  ruby $f
done
```
Weirdly enough, they all fail giving the same error:

```
/Users/alias/.rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /Users/alias/.rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/alias/Personal/repos/exercism.io/test/test_helper.rb:8:in `<top (required)>'
	from test/app/helpers/fuzzy_time_test.rb:1:in `require_relative'
	from test/app/helpers/fuzzy_time_test.rb:1:in `<main>'
```

Looking into the files which failed, they all had the same file being required:

```
require_relative '../../test_helper'
```

Looking into `test_helper.rb`, it contains the line which makes the tests fail when ran individually:

```
require 'pry'
```

To add, the statement `require 'pry'` doesn't exist anywhere else in the code.

# Possible solutions

1. Remove the instructions to run tests without the `bundle exec` prefix.
2. Update the doc to add instructions to deal with this case. Currently, it only recommends prepending `bundle exec` if the dependency is a gem installed from GitHub.
3. Remove the `require 'pry'` line.
4. Add these lines to the top of `test_helper.rb` just as how `test/integration_helper.rb` is implemented. This might be overkill because it requires every gem in the Gemfile:

```
require 'bundler'
Bundler.require
```

**Comment by kotp** [comment] 2017-06-12 08:28
Does this work for you if you do prepend the `bundle exec` prior to running the individual test? How about for your for loop?

**Comment by kotp** [comment] 2017-06-12 08:33
I believe the solution is to prepend the `bundle exec`.  Those that don't need to will likely know, and I don't think that even those that don't "need to" will lose out even if they do use it.

**Comment by Insti** [comment] 2017-06-12 11:20
I like: 
1. Remove the instructions to run tests without the `bundle exec` prefix.

**Comment by kytrinyx** [comment] 2017-06-12 15:07
Yeah, agreed. Let's make running them with bundle exec the default.

**Comment by kntsoriano** [comment] 2017-06-14 06:17
@kotp Yes, you are correct. The solution is to use `bundle exec` to run the command.

From the solution discussed, I opened #3560.

**Comment by kotp** [comment] 2017-06-14 09:41
Thank you @kntsoriano.

Remember also that it can be helpful to state "closes # " where the issue number follows the pound sign, so when it is merged, the issue is closed along with the action.  Just a pointer, taking care of it now!

Again, thank you for doing the heavy lifting!

**Closed by kotp** 2017-06-14 09:41 UTC
Labels: documentation, good first patch
