### ISSUE TITLE
Markdown in docstrings is rendered incorrectly

### ISSUE THREAD

**Issue by yurrriq** [exercism/exercism.io#2498] opened 2015-08-31 19:41 UTC
Example: http://exercism.io/submissions/3dddb5f4aaee49f8a8b893b1e5ff8800

**Comment by kytrinyx** [comment] 2015-09-01 02:22
Oh, wow. That's pretty terrible!

I wonder if this is a bug in the [rouge](https://github.com/jneen/rouge) library.

**Comment by yurrriq** [comment] 2015-09-01 02:43
Is that what GitHub uses? Somehow they deal with it: https://github.com/yurrriq/exercism/blob/clojure/allergies/src/allergies.clj

**Comment by kytrinyx** [comment] 2015-09-01 02:44
I'm not sure what GitHub uses.

**Comment by yurrriq** [comment] 2015-09-01 02:45
Hmm... I'll try do some digging on this tonight too.

**Comment by kytrinyx** [comment] 2015-09-01 02:50
Thanks.

**Comment by yurrriq** [comment] 2015-09-01 03:22
Maybe while I'm at it I can add an LFE lexer. 😈

**Comment by kytrinyx** [comment] 2015-11-12 11:14
We upgraded to a version of the syntax highlighting library that I think has a fix for this. Is this still an issue?

**Comment by yurrriq** [comment] 2015-11-12 11:25
Still looks the same to me :confused:

**Comment by kytrinyx** [comment] 2015-11-12 11:26
Gah. Darn, ok.

**Comment by mfrost** [comment] 2015-11-18 23:53
I believe this is a duplicate of #2380.

**Comment by kytrinyx** [comment] 2015-11-19 00:39
Yepp, you're right. Thanks!

**Closed by kytrinyx** 2015-11-19 00:39 UTC
Labels: bug
