### ISSUE TITLE
Lost bullet markup on C++ help page

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2831] opened 2016-04-16 06:24 UTC
![image](https://cloud.githubusercontent.com/assets/4270863/14579501/8be73bac-0369-11e6-953d-c66fc3e05c6d.png)

**Comment by LegalizeAdulthood** [comment] 2016-04-16 06:24
"Type safety", "Encapsulate...", etc., should all be bullets

**Comment by tejasbubane** [comment] 2016-04-17 12:41
Looks good in the github README. https://github.com/exercism/xcpp/blob/master/docs/ABOUT.md
Must be the issue with markdown parser. Possibly related to https://github.com/exercism/exercism.io/issues/2759 and https://github.com/exercism/exercism.io/issues/2768

**Comment by kytrinyx** [comment] 2016-04-17 13:08
Definitely related to those.

**Comment by losingkeys** [comment] 2016-04-29 01:22
The standard doesn't say anything about requiring two newlines before an unordered list: https://daringfireball.net/projects/markdown/syntax#list

However, it _does_ say something about requiring two newlines between paragraphs: https://daringfireball.net/projects/markdown/syntax#p

Also, the reference implementation "fails" in the same way as the parser you're using.

Reference implementation: https://daringfireball.net/projects/markdown/dingus

Depending on the parser I'd say it's okay just to update the markdown to have 2 newlines. Alternatively you could make it more like GH's parser to handle lists without that spacing.

**Comment by kytrinyx** [comment] 2016-04-29 18:32
There's a PR in progress that would handle lists without the spacing. We're having some trouble with dependencies, which is why this has been stuck in limbo for a while.

**Comment by kytrinyx** [comment] 2016-05-02 17:17
I'm marking this as a duplicate of https://github.com/exercism/exercism.io/issues/2759

**Closed by kytrinyx** 2016-05-02 17:17 UTC
Labels: duplicate
