### ISSUE TITLE
Deprecated exercises seen on contribute pages

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#3103] opened 2016-09-10 19:54 UTC
Some deprecated exercises are seen on language contribute pages (at the bottom).

eg. http://exercism.io/languages/elixir/contribute I can see `counter` and `point-mutations` both of which are deprecated.

I think these should not be shown in the list.

**Comment by tejasbubane** [comment] 2016-09-10 20:06
Is there are way to know which exercises are deprecated? Not sure how deprecation works.

**Comment by kytrinyx** [comment] 2016-09-10 20:37
Elixir doesn't have any deprecated exercises: https://github.com/exercism/xelixir/blob/master/config.json#L437-L439

**Comment by tejasbubane** [comment] 2016-09-11 06:00
But the README of those exercises says they are deprecated.

https://github.com/exercism/x-common/blob/master/exercises/counter/description.md
and
https://github.com/exercism/x-common/blob/master/exercises/point-mutations/description.md

If I am not wrong, the the exercises which were previously implemented are moved to deprecated list when they need to be deprecated. But since these two exercises were never implemented in `elixir` they are not in the list. Same is the case for `counter` for [ruby](http://exercism.io/languages/ruby/contribute). Hence they show up on the contribute page.

Will adding them to the deprecated list in `config.json` remove them from the page as well? Or is it a bad idea to add unimplemented exercises to the deprecated list just for the sake of removal from the page?

**Comment by kytrinyx** [comment] 2016-09-12 17:56
If they were previously implemented they should go in `deprecated` in config.json, if they haven't yet been deprecated, they should go in `foregone`.

I will write up an issue that can be submitted to all the tracks about them being deprecated (and why), and what to do with the config.json.

**Comment by rbasso** [comment] 2016-09-12 23:20
@kytrinyx , about deprecating, should we keep the deprecated exercise forever or there is a situation where the files can be safely removed?

**Comment by kytrinyx** [comment] 2016-09-19 21:51
@rbasso I haven't thought about how to eventually remove the files. I think that ideally we should be able to delete the files. We would have to do something (probably pretty straight forward) in the exercism.io codebase so that things don't blow up.

**Comment by kytrinyx** [comment] 2016-09-19 22:10
@tejasbubane I've added a new issue for `counter`and `point-mutations`.

**Comment by petertseng** [comment] 2017-03-01 02:38
Duplicate of #2938

Can close now, right? https://github.com/exercism/x-api/pull/140 and the specific exercises mentioned are now `.deprecated`.

**Comment by kytrinyx** [comment] 2017-03-02 00:23
Yepp, this is fixed.

**Closed by kytrinyx** 2017-03-02 00:23 UTC
Labels: bug
