### ISSUE TITLE
Rust ISBN verifier test miss edge cases

### ISSUE THREAD

**Issue by uranusjr** [exercism/exercism.io#3711] opened 2018-01-13 11:37 UTC
They do not ensure implementations check for ISBN length. No tests for strings that’s too short (< 10 digits), and although there are tests for > 10 digits, their checksum results are not 0 to begin with so implementations can get away just adding everything up. [Here’s an example.](http://exercism.io/submissions/ffdb9198456c4873b97faa0a5d5392cf)

**Comment by kytrinyx** [comment] 2018-01-13 17:15
Thanks so much for raising the issue, @uranusjr! I've moved this into the problem-specification repository, as I think the issue is present for all languages who implement the ISBN verifier.

Closing in favor of https://github.com/exercism/problem-specifications/issues/1096

**Closed by kytrinyx** 2018-01-13 17:15 UTC
