### ISSUE TITLE
[BUG?] debug command displays incorrect config file path

### ISSUE THREAD

**Issue by AndRAM-T** [exercism/exercism.io#2155] opened 2015-01-09 11:09 UTC
`debug` seems to be printing  some hard-coded string which is definitely not the current value of the `config` global variable. I'd expect `c:\exercism\.exercism.json` to be printed as config file instead of `C:\Documents and Settings\drequena\.exercism.json` below.

    C:\exercism>exercism --config=c:\exercism\.exercism.json debug

    **** Debug Information ****
    Exercism CLI Version: 1.9.0
    OS/Architecture: windows/386
    Home Dir: C:\Documents and Settings\drequena
    Config file: C:\Documents and Settings\drequena\.exercism.json
    API Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    API: http://exercism.io
    Exercises Directory: C:\exercism\user

**Comment by kytrinyx** [comment] 2015-01-09 14:58
Indeed, this looks odd. Thanks for reporting it!

**Comment by trodicaro** [comment] 2015-01-11 23:45
I would like to look into this, but I'm new"er" to this and would need some guidance on where would this bug be (which file or what steps you took to get to this printout).

**Comment by AndRAM-T** [comment] 2015-01-12 00:08
Thanks for your involvement. I wouldn't know where to look at as I'm not familiarized with this code base.  

As for how to get this printout, I don't really do anything very unusual: as shown, I just use the `config` argument to force the client to use some particular config file. I can tell that my configuration is actually in effect because of the displayed exercises directory, which is specified in it.

**Comment by kytrinyx** [comment] 2015-01-12 01:37
The problem is in the CLI codebase: https://github.com/exercism/cli, most likely in the https://github.com/exercism/cli/blob/master/config/config.go file. I've been pretty swamped for the past few days, but things are quieting down a little bit, and I'd be happy to help figure out what's going on.

@trodicaro are you comfortable in Go?

**Comment by kytrinyx** [comment] 2015-01-12 01:43
Here's what I get on a Mac:

Unconfigured:

```
$ exercism debug

**** Debug Information ****
Exercism CLI Version: 1.9.0
OS/Architecture: darwin/amd64
Home Dir: /Users/kytrinyx
Config file: <not configured>
API Key: <not configured>
API: http://exercism.io
Exercises Directory: /Users/kytrinyx/exercism
```

```
$ exercism configure --key=abc123
The configuration has been written to /Users/kytrinyx/.exercism.json
Your exercism directory can be found at /Users/kytrinyx/exercism
````

```
$ exercism debug

**** Debug Information ****
Exercism CLI Version: 1.9.0
OS/Architecture: darwin/amd64
Home Dir: /Users/kytrinyx
Config file: /Users/kytrinyx/.exercism.json
API Key: abc123
API: http://exercism.io
Exercises Directory: /Users/kytrinyx/exercism
```

```
$ exercism --config=~/.alternate-exercism.json debug

**** Debug Information ****
Exercism CLI Version: 1.9.0
OS/Architecture: darwin/amd64
Home Dir: /Users/kytrinyx
Config file: <not configured>
API Key: <not configured>
API: http://exercism.io
Exercises Directory: /Users/kytrinyx/exercism
```

Interestingly, I don't get a hard-coded string, but "<not configured>".

And, to make matters worse:

```
$ exercism --config=~/.other.json configure --key=xyz123
The configuration has been written to /Users/kytrinyx/.exercism.json
Your exercism directory can be found at /Users/kytrinyx/exercism
```

It appears that it's ignoring the path that is passed in.

**Comment by kytrinyx** [comment] 2015-01-12 02:02
Ah, I found the problem. Line 205 of the config.go hard-codes the value, ignoring anything else. I'll fix it and release a new build.

**Comment by kytrinyx** [comment] 2015-01-12 03:41
Fixed in exercism/cli@067e027dfb31bf3d0c4967d76ffb6d089cd001cd

**Closed by kytrinyx** 2015-01-12 03:41 UTC
Labels: bug

**Comment by kytrinyx** [comment] 2015-01-12 03:47
New release here: https://github.com/exercism/cli/releases/tag/v1.9.2

Thanks again for reporting this.

**Comment by trodicaro** [comment] 2015-01-12 16:53
Hi Katrina, we just attended a the <write/speak/code>
<http://www.writespeakcode.com/workshop-chi.html> workshop and a third of
the attendees worked on learning how to contribute to OSS under the
mentorship of Coraline Ada Ehmke. The couple of sites that got interest
were Quill.org and Exercism.io so you might have more interest coming your
way from this event :)

I would have liked to debug the issue, but I didn't even get the chance to
look at it :D. Maybe allow some extra time for future inquiries? :)

Best,
Rodica

**Comment by kytrinyx** [comment] 2015-01-12 17:21
Hi Rodica, that's awesome! I really look forward to seeing more things come in, and will definitely allow more time for future inquiries.

The codebases are kind of crazy. The CLI codebase (go) is not too bad, the x-api codebase (ruby) is very well tested and pretty straight-forward... but the exercism.io codebase is a bit of a mess.

**Comment by trodicaro** [comment] 2015-01-12 17:26
Hey, we wouldn't know the difference :)

Rodica
