### ISSUE TITLE
What looks good in preview does not look so good in nitpick message.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#2413] opened 2015-06-03 16:04 UTC
![good_in_preview](https://cloud.githubusercontent.com/assets/16747/7964893/2fecda80-09e8-11e5-8f7f-c1acc1c02750.png)

Looks good in preview.

![not_so_good_in_actual_message](https://cloud.githubusercontent.com/assets/16747/7964906/3f93b058-09e8-11e5-995f-5d62cc967e29.png)

Not so good in actual message.

**Comment by trayo** [comment] 2015-06-04 23:34
Are the exclamation marks the result of submitting the comment?

**Comment by kotp** [comment] 2015-06-05 00:57
Yes, @trayo  but they are also there to indicate the language meant to be highlighted.  Perhaps I read the GFM instructions incorrectly...

**Comment by kotp** [comment] 2015-06-05 01:00
That was it for sure.

**Comment by kotp** [comment] 2015-06-05 19:05
It doesn't quite explain why it looks good in preview though, without the exclamation point showing.   It is definitely correct to not use the exclamation point according to the GFM documentation.  So, the preview is incorrect or not consistent with this.

**Comment by kotp** [comment] 2015-06-05 19:06
Also, something else kind of flaky happening n the preview, as opposed to the actual, and that is the line number showing up and then being gone.

**Comment by tejasbubane** [comment] 2015-08-14 18:27
I just came across the same issue. It was a minor case, but since the issue is open, bringing it up here, in case it helps someone. 

The preview looks good but not the actual nitpick message.

![nitpick](https://cloud.githubusercontent.com/assets/980783/9280961/73848218-42df-11e5-826a-cbca674002e2.png)

![nitpick2](https://cloud.githubusercontent.com/assets/980783/9280968/7b6a8cfc-42df-11e5-8595-408903e3aa6e.png)

In my case, this happened because there was no empty line between the text and code snippet.

![nitpick3](https://cloud.githubusercontent.com/assets/980783/9281023/f1d7c332-42df-11e5-9e5b-a5f4dd9c325e.png)

After putting an empty line there it was all good.

**Comment by kytrinyx** [comment] 2015-08-15 09:19
Interesting. I bet we're processing the markdown differently for the two cases. It should be fairly straight forward to change the nitpick markdown to do what the preview markdown already does.

**Comment by hkockerbeck** [comment] 2015-08-30 12:33
I've come across something similar: In a nitpick (third one from top [here](http://exercism.io/submissions/b7751eb488ef4a6d93b350a82b063ff4)) I've initially started the comments in the code snippets with `#`, because it's Ruby code. That looked fine in the preview. But in the actual nitpick, the comment lines were huge. Probably they've been interpreted as headers/headlines because of the  `#`, even though they were inside a code block. I've changed the comments to PHP style as a hotfix.

**Comment by kytrinyx** [comment] 2015-08-30 14:21
Thanks @hkockerbeck -- it's useful to have some extra test cases for this.

**Comment by tejasbubane** [comment] 2015-09-03 07:25
@kytrinyx The code for processing markdown is same in both the cases [here is the preview](https://github.com/exercism/exercism.io/blob/master/lib/app/routes/comments.rb#L27) and [here is the submission](https://github.com/exercism/exercism.io/blob/master/lib/exercism/comment.rb#L12).

Also now I am not able to reproduce my specific case (in previous comment) on my localhost.

**Comment by kytrinyx** [comment] 2015-09-03 16:15
That's an interesting twist. I wonder if the body is exactly the same in both cases, or whether it strips some whitespace or something in one of them.

**Comment by mfrost** [comment] 2015-11-18 23:35
The original report describes the difference between a `codespan` and `codefence` in [redcarpet](https://github.com/vmg/redcarpet). I've had a bit of trouble tracking down the original source of the discrepancy between preview and rendered comments. I can do a git-bisect if we want to really chase it down.

As per @tejasbubane's last comment, code block formatting seems to have been fixed in [this commit](https://github.com/exercism/exercism.io/commit/7ea91da42535c33952d3c086f614dd1aebacea47). Note that the `gsub` there ensures there are leading and trailing newlines.

There may be comments in the production database that exhibit the incorrect markup because rendered content [is stored](https://github.com/exercism/exercism.io/blob/master/lib/exercism/comment.rb#L11-L14).

Let me know if you'd like me to track down at what point the execution paths differed.

**Comment by kytrinyx** [comment] 2015-11-18 23:38
Ahhh. Let me re-generate all the html first, and see if it's still a problem.

**Comment by kytrinyx** [comment] 2015-11-19 00:30
Regenerated.

**Comment by kytrinyx** [comment] 2015-11-28 15:27
This looks fixed to me (tested by writing a new comment). I'm closing it, but please holler if there still seem to be cases that are not fixed.

**Closed by kytrinyx** 2015-11-28 15:27 UTC
Labels: bug
