### ISSUE TITLE
Github username change causing lost history

### ISSUE THREAD

**Issue by gibfahn** [exercism/exercism.io#3100] opened 2016-09-10 12:29 UTC
I recently changed my username on Github (from `gibfahn` to `gibm`), and now when I log in to Exercism.io, my old submissions are no longer associated with my account, and they don't have a username associated with them at all.

I'm not sure how the Github account API handles these changes, but it should hopefully be possible to maintain history somehow. 
#### Example:

[Submission before username change (as gibm)](http://exercism.io/submissions/667727a612944dc9b81bbe80bb954e7c)
[Submission since username change (as gibfahn)](http://exercism.io/submissions/3e67a218dfed47baaa588ba43cf8559a)

**Comment by kytrinyx** [comment] 2016-09-10 13:39
Hi @gibfahn this is a bug, and I believe we had this working before. We store the GitHub user id in all cases, so we should be able to reassociate the exercises with your new username.

I'm going to dig into this today and I will let you know what I find out.

**Comment by kytrinyx** [comment] 2016-09-10 14:29
@gibfahn It doesn't look like you changed your username, but rather that you stopped using the old account as @gibm and started using the new one as @gibfahn.

I have reassociated the old exercises with your @gibm account.

I still need to figure out why the username was removed from that user record.

**Comment by kytrinyx** [comment] 2016-09-10 15:36
I still haven't figured out the exact reproduction steps for this.

We have code to detect conflicts when people are logging in via GitHub: https://github.com/exercism/exercism.io/blob/master/lib/exercism/user.rb#L47-L67

This is important, because when you change your GitHub username, it becomes available for another person to use.

In this case, though, I don't understand how that happened, since these are completely independent GitHub users, they just happen to be owned by the same person.

**Comment by gibfahn** [comment] 2016-09-10 17:20
@kytrinyx So what happened was I switched account names. So the account that was originally called `gibm` became `gibfahn`, and `gibfahn` became `gibm` (so anyone clicking on an `@gibm` would still be able to find me). I suspect this is what caused the problem.

Probably not a common thing to happen though!

**Comment by kytrinyx** [comment] 2016-09-10 19:36
Ahhh! That actually makes a lot of sense. The first conflict on the name would set the username to empty on the prior account, and then nothing would set it back, unless you logged in with the first account again on Exercism.

> Probably not a common thing to happen though!

Hopefully!

We should still figure out how to avoid having this happen, if we can. I'll think about it.

**Comment by jtigger** [comment] 2016-11-04 12:22
Might be related to #3227.

**Comment by kytrinyx** [comment] 2017-03-29 22:13
It's not clear to me what scenario we should support. Since this affects a very small number of users, I'm going to close this. However, if someone thinks it's important to fix this, please open up a new issue in the exercism/discussions repository.

Please describe the reproduction steps and suggest a way that you think it _should_ work.

**Closed by kytrinyx** 2017-03-29 22:13 UTC
Labels: bug
