### ISSUE TITLE
migration page still showing depending on url used

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism.io#3854] opened 2018-07-16 04:23 UTC
I went to a link I had in history "https://www.exercism.io" when using this link I still get the "Please bear with us while we migrate...". 

The good news if you go to any other url you get to the site. So maybe there is still some remnants of the migration in the server configuration.

**Comment by iHiD** [comment] 2018-07-17 00:05
Closing as duplicate of #3861 - Thanks though! :)

**Closed** 2018-08-01 13:16 UTC
Labels: type/duplicate
