### ISSUE TITLE
No comment box shown?

### ISSUE THREAD

**Issue by lathspell** [exercism/exercism.io#4168] opened 2018-08-05 21:25 UTC
I see lots of comments under other peoples solutions but no input box where I could leave a comment. Is this a bug?

**Comment by NobbZ** [comment] 2018-08-05 21:39
Possible duplicate of #4156.

**Comment by iHiD** [comment] 2018-08-05 22:02
Thanks for reporting. As @NobbZ said, this is a duplicate. It's something that will be added shortly. Thanks :)

**Closed by iHiD** 2018-08-05 22:02 UTC
Labels: type/duplicate
