### ISSUE TITLE
Languages page not displaying properly on Safari 9

### ISSUE THREAD

**Issue by nathanbwright** [exercism/exercism.io#3325] opened 2016-12-23 17:27 UTC
I just visited http://exercism.io/languages in Safari 9 and noticed the following issue.

![exercism](https://cloud.githubusercontent.com/assets/4740018/21459157/1fdd9b3a-c8f9-11e6-93e1-23e2c2d82e15.png)

It looks like each of the rows is getting rendered separately, and there is a issue with the way Safari is rendering the padding. Chrome/Firefox appear to be rendering fine. Could we move this to a completely flex boxed layout? What version of IE is "officially" supported? 

Here are is the browser support for flex box: http://caniuse.com/#search=flexbox

**Comment by bernardoamc** [comment] 2016-12-23 17:36
Hey @nathanbwright, last time I checked (2 months ago) it was something like this in relation to flexbox:

- Chrome: Doing well based on the versions used.
- Firefox: 7% of the users still use versions below 47
- Safari: 25% of the users still use versions below 9.1
- Opera: 10% of the users still use versions below 39
- Edge: 1% of the users still use versions below 13
- IE: 2% of the users using versions below 11, but IE 11 just provides partial support.

**Comment by behrtam** [comment] 2017-03-22 17:39
It doesn't work with Safari 10 as well.

**Comment by lukaszklis** [comment] 2017-05-18 07:49
The problem is caused by having `display: flex` applied to `#languages .row`. Is there any reason why you wanted to have flexbox used there in the first place?

**Comment by kytrinyx** [comment] 2017-05-19 17:47
@lukaszklis omg thank you! I have no idea about anything on the front-end, so most of it is either fixed by people who happen to know more than me (the bar is very low), or done badly and wrong by me.

It could be worth running blame on it and pinging the author here to see if they remember anything about it.

**Comment by behrtam** [comment] 2017-05-19 19:04
https://github.com/exercism/exercism.io/pull/3082 by @alexcameron89

**Comment by lukaszklis** [comment] 2017-05-19 19:09
I can look into it this weekend once I get on my laptop (traveling at the moment with access to only to my smartphone). Feel free to assign the issue to me—will gladly help. :)

**Comment by kytrinyx** [comment] 2017-05-19 19:10
Awesome, thanks @lukaszklis. It's all yours!

**Comment by nathanbwright** [comment] 2017-05-19 19:30
If I'm not mistaken this is due to the way Safari handles `:before` and `:after` elements. See this SO answer for an explanation: http://stackoverflow.com/a/36476586/2529285.

**Comment by lukaszklis** [comment] 2017-05-19 19:35
Indeed, the pseudo-elements are added just because we're using .row which applies those as part of the clearfix for the grid. One of the solutions here is to use a pure flex box based styling and removing the Bootstrap classes.

**Closed** 2017-05-21 16:57 UTC
Labels: bug, ux
