### ISSUE TITLE
Reconciling changes made to exercise test suites

### ISSUE THREAD

**Issue by benwurth** [exercism/exercism.io#1891] opened 2014-09-28 01:40 UTC
Hi, Everyone!

I recently submitted some exercise code to exercism.io (specifically Javascript's [Bob](https://github.com/exercism/xjavascript/tree/master/bob) exercise). I had made sure that the code was passing the test suite before uploading, but one of my nitpicks pointed out that my code should not have been able to pass due to a typo.

It turns out that in-between the time that I fetched the exercise and uploaded my results the test suite had been slightly altered in this commit: https://github.com/exercism/xjavascript/commit/38b9114a0453d8fc7ad08813325787f369fefa02. When my nitpicker referenced the test suite for Bob on my submission page, they found the new version, leading them to believe that my code should not have been able to pass its tests.

It would be helpful if there were a way for the command line tool to let the user know that an exercise has been updated (perhaps it could check when new exercises are fetched) and give the user a simple command for fetching a new version of the test suite and/or README.

In addition, it would also be helpful if the test suite code attached to a submission online displayed the version of the suite that the submitter downloaded and actually ran to test their code.

Regardless of how to proceed, this is an issue that really ought to be addressed. 

Sorry for the long post, and thanks for your consideration!

Best,
Ben

**Comment by kytrinyx** [comment] 2015-03-28 16:48
This is a duplicate of #1657

**Closed by kytrinyx** 2015-03-28 16:48 UTC
