### ISSUE TITLE
Leaving Track doesn't clear solutions.

### ISSUE THREAD

**Issue by BradleyJohnson** [exercism/exercism.io#4109] opened 2018-08-01 22:47 UTC
Not sure if intended or not, but the warning message indicates track progress will be lost. In my case, this is the desired outcome but I cannot clear the solutions.

**Comment by iHiD** [comment] 2018-08-01 22:54
Thanks for reporting that @BradleyJohnson! :) I'm going to close this as a duplicate of https://github.com/exercism/exercism.io/issues/3986.

**Closed by iHiD** 2018-08-01 22:54 UTC
