### ISSUE TITLE
mentors.exercism.io has outdated references from pre-launch

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism.io#4028] opened 2018-07-21 13:05 UTC
Both the mentors site and the google sign-up form refer to the original Exercism and the beta (v2).

**Comment by Ornataweaver** [comment] 2018-07-21 13:11
The same thing on https://docs.google.com/forms/d/e/1FAIpQLSfDD7DNuFwjvPBKRojTgb4ae1XlLmJS9H6g1lMB_BTZy_8UOw/viewform:
"You can find more information about mentoring at http://mentoring.exercism.io and you can check out a beta of the new site at https://v2.exercism.io"

**Comment by iHiD** [comment] 2018-07-23 12:03
Closing as duplicate of https://github.com/exercism/exercism.io/issues/4033

**Closed by iHiD** 2018-07-23 12:03 UTC
