### ISSUE TITLE
Building word_count.cpp always fails.

### ISSUE THREAD

**Issue by drzoidberg33** [exercism/exercism.io#2616] opened 2015-11-15 16:33 UTC
Don't know if I'm doing something wrong or if it's just a boost issue.

Running OS 10.11.2
Boost v1.59.0
Xcode 7.1.1

Trying to build in Xcode just fails with no output.

Creating another build and trying to to use make from command line gives me this:

```
Tims-MacBook-Pro-13:build2 tim$ make
Scanning dependencies of target word-count
[ 33%] Building CXX object CMakeFiles/word-count.dir/word_count_test.cpp.o
In file included from /Users/tim/exercism/cpp/word-count/word_count_test.cpp:3:
In file included from /usr/local/include/boost/test/unit_test.hpp:18:
In file included from /usr/local/include/boost/test/test_tools.hpp:38:
In file included from /usr/local/include/boost/test/tools/old/impl.hpp:24:
/usr/local/include/boost/test/tools/detail/print_helper.hpp:50:14: error: invalid operands to binary expression ('std::ostream'
      (aka 'basic_ostream<char>') and 'const std::__1::pair<const std::__1::basic_string<char>, int>')
        ostr << t;
        ~~~~ ^  ~
/usr/local/include/boost/test/tools/detail/print_helper.hpp:172:5: note: in instantiation of member function
      'boost::test_tools::tt_detail::print_log_value<std::__1::pair<const std::__1::basic_string<char>, int> >::operator()' requested here
    print_log_value<T>()( ostr, ph.m_t );
    ^
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:66:19: note: in instantiation of function template specialization
      'boost::test_tools::tt_detail::operator<<<std::__1::pair<const std::__1::basic_string<char>, int> >' requested here
    targ.stream() << t;
                  ^
/usr/local/include/boost/test/tools/old/impl.hpp:212:19: note: in instantiation of function template specialization 'boost::operator<<<char,
      boost::test_tools::tt_detail::print_helper_t<std::__1::pair<const std::__1::basic_string<char>, int> > >' requested here
                  << ::boost::test_tools::tt_detail::print_helper(*left_begin)
                  ^
/Users/tim/exercism/cpp/word-count/word_count_test.cpp:30:5: note: in instantiation of function template specialization
      'boost::test_tools::tt_detail::equal_coll_impl::operator()<std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<std::__1::basic_string<char>,
      int>, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *> *, long> >,
      std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<std::__1::basic_string<char>, int>,
      std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, int>, void *> *, long> > >' requested here
    REQUIRE_EQUAL_CONTAINERS(expected, actual);
    ^
/Users/tim/exercism/cpp/word-count/word_count_test.cpp:22:5: note: expanded from macro 'REQUIRE_EQUAL_CONTAINERS'
    BOOST_REQUIRE_EQUAL_COLLECTIONS(left_.begin(), left_.end(), right_.begin(), right_.end())
    ^
/usr/local/include/boost/test/tools/old/interface.hpp:245:5: note: expanded from macro 'BOOST_REQUIRE_EQUAL_COLLECTIONS'
    BOOST_TEST_TOOL_IMPL( 1, ::boost::test_tools::tt_detail::equal_coll_impl(),         \
    ^
/usr/local/include/boost/test/tools/old/interface.hpp:66:9: note: expanded from macro 'BOOST_TEST_TOOL_IMPL'
        BOOST_JOIN( BOOST_TEST_TOOL_PASS_PRED, frwd_type )( P, ARGS ),          \
        ^
note: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:88:1: note: expanded from here
BOOST_TEST_TOOL_PASS_PRED1
^
/usr/local/include/boost/test/tools/old/interface.hpp:48:49: note: expanded from macro 'BOOST_TEST_TOOL_PASS_PRED1'
#define BOOST_TEST_TOOL_PASS_PRED1( P, ARGS ) P BOOST_PP_SEQ_TO_TUPLE(ARGS)
                                                ^
/usr/local/include/boost/preprocessor/seq/to_tuple.hpp:21:40: note: expanded from macro 'BOOST_PP_SEQ_TO_TUPLE'
#    define BOOST_PP_SEQ_TO_TUPLE(seq) (BOOST_PP_SEQ_ENUM(seq))
                                       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:207:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'const void *' for 1st
      argument; take the address of the argument with &
    basic_ostream& operator<<(const void* __p);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:191:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to
      'std::__1::basic_ostream<char> &(*)(std::__1::basic_ostream<char> &)' for 1st argument
    basic_ostream& operator<<(basic_ostream& (*__pf)(basic_ostream&));
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:192:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'basic_ios<char_type,
      traits_type> &(*)(basic_ios<char_type, traits_type> &)' for 1st argument
    basic_ostream& operator<<(basic_ios<char_type, traits_type>&
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:194:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'std::__1::ios_base
      &(*)(std::__1::ios_base &)' for 1st argument
    basic_ostream& operator<<(ios_base& (*__pf)(ios_base&));
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:195:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'bool' for 1st argument
    basic_ostream& operator<<(bool __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:196:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'short' for 1st argument
    basic_ostream& operator<<(short __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:197:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'unsigned short' for 1st
      argument
    basic_ostream& operator<<(unsigned short __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:198:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'int' for 1st argument
    basic_ostream& operator<<(int __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:199:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'unsigned int' for 1st
      argument
    basic_ostream& operator<<(unsigned int __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:200:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'long' for 1st argument
    basic_ostream& operator<<(long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:201:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'unsigned long' for 1st
      argument
    basic_ostream& operator<<(unsigned long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:202:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'long long' for 1st
      argument
    basic_ostream& operator<<(long long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:203:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'unsigned long long' for
      1st argument
    basic_ostream& operator<<(unsigned long long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:204:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'float' for 1st argument
    basic_ostream& operator<<(float __f);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:205:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'double' for 1st
      argument
    basic_ostream& operator<<(double __f);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:206:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to 'long double' for 1st
      argument
    basic_ostream& operator<<(long double __f);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:208:20: note: candidate
      function not viable: no known conversion from 'const std::__1::pair<const std::__1::basic_string<char>, int>' to
      'basic_streambuf<char_type, traits_type> *' for 1st argument
    basic_ostream& operator<<(basic_streambuf<char_type, traits_type>* __sb);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:785:1: note: candidate
      function [with _CharT = char, _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'char' for 2nd argument
operator<<(basic_ostream<_CharT, _Traits>& __os, char __cn)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:818:1: note: candidate
      function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'char' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, char __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:825:1: note: candidate
      function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'signed char' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, signed char __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:832:1: note: candidate
      function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'unsigned char' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, unsigned char __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:846:1: note: candidate
      function [with _CharT = char, _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'const char *' for 2nd argument
operator<<(basic_ostream<_CharT, _Traits>& __os, const char* __strn)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:892:1: note: candidate
      function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'const char *' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, const char* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:899:1: note: candidate
      function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'const signed char *' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, const signed char* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:907:1: note: candidate
      function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'const unsigned char *' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, const unsigned char* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1086:1: note: candidate
      function [with _CharT = char, _Traits = std::__1::char_traits<char>] not viable: no known conversion from 'const std::__1::pair<const
      std::__1::basic_string<char>, int>' to 'const std::__1::error_code' for 2nd argument
operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __ec)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:778:1: note: candidate
      template ignored: deduced conflicting types for parameter '_CharT' ('char' vs. 'std::__1::pair<const std::__1::basic_string<char>, int>')
operator<<(basic_ostream<_CharT, _Traits>& __os, _CharT __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:839:1: note: candidate
      template ignored: could not match 'const _CharT *' against 'std::__1::pair<const std::__1::basic_string<char>, int>'
operator<<(basic_ostream<_CharT, _Traits>& __os, const _CharT* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1094:1: note: candidate
      template ignored: could not match 'shared_ptr' against 'pair'
operator<<(basic_ostream<_CharT, _Traits>& __os, shared_ptr<_Yp> const& __p)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1101:1: note: candidate
      template ignored: could not match 'bitset' against 'pair'
operator<<(basic_ostream<_CharT, _Traits>& __os, const bitset<_Size>& __x)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1063:5: note: candidate
      template ignored: disabled by 'enable_if' [with _Stream = std::__1::basic_ostream<char> &, _Tp = std::__1::pair<const
      std::__1::basic_string<char>, int>]
    !is_lvalue_reference<_Stream>::value &&
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1077:1: note: candidate
      template ignored: could not match 'basic_string' against 'pair'
operator<<(basic_ostream<_CharT, _Traits>& __os,
^
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:64:1: note: candidate template ignored: could not match 'basic_wrap_stringstream'
      against 'basic_ostream'
operator<<( basic_wrap_stringstream<CharT>& targ, T const& t )
^
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:109:1: note: candidate template ignored: could not match 'basic_wrap_stringstream'
      against 'basic_ostream'
operator<<( basic_wrap_stringstream<CharT>& targ, basic_wrap_stringstream<CharT>& src )
^
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:121:1: note: candidate template ignored: could not match 'basic_wrap_stringstream'
      against 'basic_ostream'
operator<<( basic_wrap_stringstream<CharT>& targ, std::ios_base& (BOOST_TEST_CALL_DECL *man)(std::ios_base&) )
^
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:131:1: note: candidate template ignored: could not match 'basic_wrap_stringstream'
      against 'basic_ostream'
operator<<( basic_wrap_stringstream<CharT>& targ, std::basic_ostream<Elem,Tr>& (BOOST_TEST_CALL_DECL *man)(std::basic_ostream<Elem, Tr>&) )
^
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:141:1: note: candidate template ignored: could not match 'basic_wrap_stringstream'
      against 'basic_ostream'
operator<<( basic_wrap_stringstream<CharT>& targ, std::basic_ios<Elem, Tr>& (BOOST_TEST_CALL_DECL *man)(std::basic_ios<Elem, Tr>&) )
^
/usr/local/include/boost/smart_ptr/shared_ptr.hpp:891:64: note: candidate template ignored: could not match 'shared_ptr' against 'pair'
template<class E, class T, class Y> std::basic_ostream<E, T> & operator<< (std::basic_ostream<E, T> & os, shared_ptr<Y> const & p)
                                                               ^
1 error generated.
make[2]: *** [CMakeFiles/word-count.dir/word_count_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/word-count.dir/all] Error 2
make: *** [all] Error 2
```

Any ideas what I'm doing wrong? I can build the application fine on it's own (without the test).

**Comment by kytrinyx** [comment] 2015-11-15 17:07
@RichardWigley do you know what might be happening with this?

**Comment by RichardWigley** [comment] 2015-11-17 09:47
It sounds like the problem is specific to one exercise? If that's the case then opening an issue on [C++ repository](https://github.com/exercism/xcpp) might make sense?  [I looked at the word count question and there have been no recent changes.](https://github.com/exercism/xcpp/tree/master/word-count).

I haven't looked at C++ for over 10 years and it was Visual Studio on Windows machine :)  I tried to follow the instructions doing 'bob' on my mac but got lost; no help I'm afraid.

**Comment by kytrinyx** [comment] 2015-11-17 14:44
D'oh. I meant to tag Richard Thompson, not Richard Wigley who is @LegalizeAdulthood! Sorry about that!

**Comment by RichardWigley** [comment] 2015-11-17 15:10
No worries; I am enjoying not programming C++ even more ;-)

**Comment by LegalizeAdulthood** [comment] 2015-11-20 20:28
This looks to be a problem with boost.test in 1.59.  In Boost 1.59 they changed Boost.Test considerably.  Try Boost 1.55 and see if you still have the same problem.

**Comment by LegalizeAdulthood** [comment] 2016-01-04 18:06
I have a fix for this in progress.  I am waiting on some test feedback before deployment.

**Comment by GReaperEx** [comment] 2016-03-01 12:50
Yep, it fixes it. I'm using Boost 1.60 and it works flawlessly.

**Comment by LegalizeAdulthood** [comment] 2016-03-01 21:48
I think I'm going to push my changes to master for xcpp.  It might still be broken for some Mac users, but since it's already broken for them, it won't be any worse.

**Comment by kytrinyx** [comment] 2016-03-03 17:39
Yeah, good call, @LegalizeAdulthood

**Closed** 2016-10-24 01:01 UTC
