### ISSUE TITLE
Checking for track completion

### ISSUE THREAD

**Issue by Tonkpils** [exercism/exercism.io#2375] opened 2015-04-29 20:36 UTC
Following the discussion from https://github.com/exercism/cli/issues/187#issuecomment-96265371 and relating to https://github.com/exercism/cli/issues/53

We need a way to track how many problems the user has submitted vs how many problems a track has. This will allow the CLI to let the user know when they've completely exhausted a track for a certain language.

**Comment by pminten** [comment] 2015-05-03 15:46
Good idea. It's a bit more complicated though than just comparing two numbers since exercises are sometimes removed from tracks after a user has already done them.

**Comment by kytrinyx** [comment] 2015-05-03 16:53
I think we should add redis to the x-api, and whenever someone fetches a particular exercise, we could store that in a set for that user/language track. This would make it very quick and easy to keep track of what problems someone has completed, and which ones are remaining, while including/excluding deprecated exercises as appropriate.

**Comment by lcowell** [comment] 2015-05-06 15:33
Is the information we need stored in the database ? Wouldn't it be something like:

```SQL
SELECT
  user_exercises.slug
FROM user_exercises
WHERE user_id=11235
  AND language='ruby'
  AND state='done'
ORDER BY completed_at;
```

This could even be modified to return the slugs of the most recently completed exercises for each language.

**Comment by kytrinyx** [comment] 2015-05-07 03:39
Yeah, this information is in the database, but the x-api (problems API) is in a stand-alone application, so we either need to make a request to the exercism.io api, or we need to store a little bit of data in the x-api. I'd prefer storing the data in duplicate in the x-api, since we can do that on fetch without having to talk to exercism, and it's going to be very light-weight/fast.

We'll need to write a migration that has a query something like what you wrote--though it would be all states, not just the completed ones.

**Comment by kytrinyx** [comment] 2015-11-27 19:47
I've changed my mind about how I want to solve this.

I'm rewriting the problems API (x-api), and it's not going to know anything about users, nor will it make calls to the exercism.io api.

Instead, we're going to make a new endpoint on exercism.io that makes the fetch call to x-api, and also figures out things like how many of the problems the user has not solved. This endpoint will be able to figure out whether or not the user has completed the track.

See https://github.com/exercism/x-api/issues/75.

I'm closing this as a duplicate of https://github.com/exercism/exercism.io/issues/2358

**Closed by kytrinyx** 2015-11-27 19:47 UTC
