### ISSUE TITLE
code snippet not printed correctly in ~/bin PATH instructions

### ISSUE THREAD

**Issue by ballPointPenguin** [exercism/exercism.io#4013] opened 2018-07-19 21:23 UTC
In the Getting Started instructions (for Python) I see this in the **Adding ~/bin to $PATH in Bash** section.

see screenshot:
![screenshot from 2018-07-19 14-21-11](https://user-images.githubusercontent.com/35609/42970785-1c6f7516-8b5f-11e8-854c-670e819de4d2.png)

I'm not sure exactly what the code should look like, but right now it looks like this:
```
<a href="javascript:void(0)" data-passage=" &quot;:$PATH:&quot; == *&quot;:$HOME/bin:&quot;* "> ":$PATH:" == *":$HOME/bin:"* </a> && echo "~/bin is in PATH" || echo "~/bin is not in PATH"
```

**Comment by iHiD** [comment] 2018-07-28 20:52
Thanks for reporting. I believe this is a duplicate of https://github.com/exercism/exercism.io/issues/3803

**Closed** 2018-07-28 20:54 UTC
