### ISSUE TITLE
unable to submit (HTTP: 400) - duplicate of previous iteration

### ISSUE THREAD

**Issue by hebertjulio** [exercism/exercism.io#3109] opened 2016-09-15 19:34 UTC
After I deleted exercise, I don't can submit it again.

[hjulio@74372 Exercism]$ exercism submit python/hello-world/hello_world.py
2016/09/15 16:31:04 unable to submit (HTTP: 400) - duplicate of previous iteration

**Comment by kotp** [comment] 2016-09-15 21:32
![2016-09-15_650x251_scrot](https://cloud.githubusercontent.com/assets/16747/18568258/5849a05e-7b6a-11e6-859c-f8c22b8b5625.png)

This is what I did, and it seems like it submits.  Can you show what you did so that hopefully it can be reproduced?

**Comment by hebertjulio** [comment] 2016-09-16 00:28
I deleted my first exercise by web interface, before I submitted it three times. Now when I try submit it again, a HTTP error 400 occurs.

> **** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/hebert
Config file: /home/hebert/.exercism.json
Exercises Directory: /home/hebert/Development/exercism.io
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 149.904585ms
	* API: http://exercism.io [connected] 330.018038ms
	* XAPI: http://x.exercism.io [connected] 921.376183ms

> [hebert@5470 hello-world]$ exercism submit hello_world.py 
2016/09/15 21:27:24 unable to submit (HTTP: 400) - duplicate of previous iteration

**Comment by rbasso** [comment] 2016-09-16 10:28
> Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64

I have a very similar setup, but I couldn't reproduce your problem.

I checked online that your submission isn't there. So, could you please try to upload it again and see if the problem persists?

Can you reproduce the problem with another exercise and list the steps to reproduce the error?

**Comment by hebertjulio** [comment] 2016-09-16 10:47
@rbasso this problem occurs only with the first python exercise, the another exercises this error no occurs. I try submit my first python exercise "exercism submit python/hello-world/hello_world.py" and get this error again.

**Comment by rbasso** [comment] 2016-09-16 11:06
Maybe something stuck in the server...

**Comment by hebertjulio** [comment] 2016-09-17 12:01
@kotp @rbasso This error occurs because when I try to send again the same exercise I deleted before, the same hash is generated and then tried to create an iteration that already existed but was logically excluded before. I solved this error by changing the source code of the exercise, so that a new hash is generated.

**Comment by kytrinyx** [comment] 2016-09-19 19:56
> duplicate of previous iteration

The logic for this is here: https://github.com/exercism/exercism.io/blob/master/lib/exercism/use_cases/attempt.rb#L32-L34

It's not generating a hash of the solution, it checks the actual text of the solution against the previous solution. I don't think it checks against deleted solutions (we cache deleted solutions, but they shouldn't be checked in this code path).

Maybe this is triggering against the NullSubmission?

**Comment by hebertjulio** [comment] 2016-09-20 01:37
Yes @kytrinyx, this explains why unable to submit the solution after changing the solution text. Why no undo delete previous solution, instead raise duplicate exception?

**Comment by kytrinyx** [comment] 2016-10-01 22:55
> Why no undo delete previous solution, instead raise duplicate exception?

Ah, that's a great suggestion. We didn't have deletion with undo back when the duplicate exception was introduced. This would be a good fix.

**Comment by kytrinyx** [comment] 2017-03-29 22:16
There's been no movement on this for 6 months, so I'm going to go ahead and close it. If someone runs into this problem again, then they can post a new issue, and we can reconsider whether it's important to prioritize it over other things.

Thanks!

**Closed by kytrinyx** 2017-03-29 22:16 UTC
Labels: bug
