### ISSUE TITLE
Seed data for development

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#4051] opened 2018-07-23 20:14 UTC
There is no seed data at the moment. After running project setup, I don't have any track/exercise data. 

In previous version of exercism, we had some nice seed data which helped contributors up and running. It would be nice to have something like that.

**Comment by iHiD** [comment] 2018-07-24 09:21
This is because #4050 failed. I'll close this as the issue is over there, not here.

**Closed by iHiD** 2018-07-24 09:21 UTC
