### ISSUE TITLE
The SumOfMultiples Haskell exercise is not clear on what the sumOfMultiplesDefault function should do

### ISSUE THREAD

**Issue by habibalamin** [exercism/exercism.io#2654] opened 2015-12-06 11:20 UTC
I struggled to comprehend what the README was saying on what `sumOfMultiples` should do, but it says nothing about `sumOfMultiplesDefault`.

**Comment by kytrinyx** [comment] 2015-12-06 20:21
The README is not language-specific, it just describes the generic problem, and then whichever language tracks want to implement the exercise with whatever they need to make it idiomatic.

I can't speak to the Haskell exercise. @etrepum is there something we can do to make this less confusing?

**Comment by petertseng** [comment] 2016-01-31 19:47
I'm pretty sure that `sumOfMultiplesDefault` should be for the test suite only. Students shouldn't have to implement it at all. The fact that there is a "default" of `[3, 5]` is a detail of the test cases and implementations shouldn't need to know about it.

**Comment by petertseng** [comment] 2016-01-31 19:57
Unfortunately I have to eat my words. The [readme](https://github.com/exercism/x-common/blob/master/sum-of-multiples.md) says no factors specified means default to `[3, 5]`. So that's what `sumOfMultiplesDefault` is asking for. So I guess we're back to the question of "how to make this clearer?"

**Comment by habibalamin** [comment] 2016-01-31 20:10
Looks like the README was already updated the day I created this issue. Look at the latest commit date on the README you linked.

**Comment by petertseng** [comment] 2016-01-31 20:13
Ahhhh good eye; I totally missed that. In that case, maybe with the change to the README it is now clear enough, and the problem is solved...?

**Comment by habibalamin** [comment] 2016-01-31 20:15
I wouldn't be able to say, I'm afraid, since I now know what's required, my perspective is almost moot. It's definitely clear*er*. I guess we close this issue, and if someone else opens a similar issue, we'll know, right?

**Comment by petertseng** [comment] 2016-01-31 20:21
> I guess we close this issue, and if someone else opens a similar issue, we'll know, right?

I suppose that is reasonable.

I liked the proposal of "no defaults!" better, but that solution requires at least a change to the readme and a sweep through all tracks implementing that problem to see whether they do the right thing, and that may be a project for another day (though there is related work tracked at https://github.com/exercism/todo/issues/20 and https://github.com/exercism/todo/issues/154)

**Comment by habibalamin** [comment] 2016-01-31 20:26
If the option of no defaults is on the table, I would say that's preferable too, but of course, it's the choice of whoever has to go and do that work.

**Comment by kytrinyx** [comment] 2016-02-02 18:24
> If the option of no defaults is on the table

Yeah, that's always an option.

I don't have the bandwidth to think through the pros/cons of "no defaults", but if someone else can make a good case for it, I'd be happy to write up the issues etc.

**Comment by kytrinyx** [comment] 2016-03-12 22:05
I've opened a ticket in x-common to make the "no defaults" change: https://github.com/exercism/x-common/issues/198

**Comment by petertseng** [comment] 2016-08-15 05:45
Closed by https://github.com/exercism/x-common/issues/198

**Closed** 2016-10-24 01:00 UTC
