### ISSUE TITLE
Move account progress from one account to another github associated account

### ISSUE THREAD

**Issue by jwalder3** [exercism/exercism.io#6392] opened 2022-06-01 15:23 UTC

**Comment by jwalder3** [comment] 2022-06-01 15:24
Hi,

I will soon lose access to my current github account which is associated with all the progress on Exercism. Would it be possible to move my progress to a personal Github account?

Thanks in advance

**Comment by iHiD** [comment] 2022-06-01 16:17
Closing as duplicate of https://github.com/exercism/exercism/issues/6391

**Closed as completed by iHiD** 2022-06-01 16:17 UTC
