### ISSUE TITLE
Unable to access bash track on the exercism.io

### ISSUE THREAD

**Issue by hgvanpariya** [exercism/exercism.io#4010] opened 2018-07-19 17:54 UTC
On exercism.io, when I go to tracks and click on bash ( https://exercism.io/my/tracks/bash ), it is redirecting to error page.

<img width="1239" alt="screen shot 2018-07-19 at 11 04 14 pm" src="https://user-images.githubusercontent.com/1458819/42960895-d51eac1c-8baa-11e8-8d09-31984e08bd36.png">

**Comment by guygastineau** [comment] 2018-07-19 18:18
@hgvanpariya
- thank you for opening this issue.
- for anyone just coming to this issue we started the discussion in exercism/bash#166

**Comment by guygastineau** [comment] 2018-07-19 18:20
@hgvanpariya
What browser are you using?

It works for me on chromium and on mobile with brave browser.

**Comment by hgvanpariya** [comment] 2018-07-19 18:26
I've checked in following environment:
1. Windows + Google Chrome -> Not working
2. Mac + Google Chrome -> Not working
3. Mac + Firefox -> Not working

**Comment by guygastineau** [comment] 2018-07-19 18:31
Hmm, mine is working in chromium on an arch Linux machine. I don't have any way to test for Mac or windows.  Do you have a way to test in Linux?

**Comment by guygastineau** [comment] 2018-07-19 18:35
I just reproduced the same error by going to your link above without being logged in to exercism.io.  
- are you logged in when you are trying to open the page?

**Comment by hgvanpariya** [comment] 2018-07-19 18:36
yes I'm logged in via `github` and then clicked on `bash`

**Comment by guygastineau** [comment] 2018-07-19 18:40
Thank your clarification. 
Unfortunately, I'm out of ideas.
- hopefully someone see this issue and can sort it out.

**Comment by hgvanpariya** [comment] 2018-07-19 18:41
is it because, I've logged in with github ?

**Comment by NobbZ** [comment] 2018-07-19 18:42
Since the bash track is the very first that got activated after the relaunch, let me ask this:

Whom of you joined the track during v1 (by submitting at least one solution) and who did join only after the launch?

Are those that can use the track in the first group? Is there anyone in the first group not able to use the track?

PS: I submitted during v1 and can access the track.

**Comment by guygastineau** [comment] 2018-07-19 18:42
No, I'm logging in with GitHub too, so I don't think that is the problem.

**Comment by hgvanpariya** [comment] 2018-07-19 18:43
I'm also not able to access `Update Privacy settings` : https://exercism.io/my/settings/update_user_tracks  ( Will this be linked somehow ?)

**Comment by guygastineau** [comment] 2018-07-19 18:44
@NobbZ I joined during V1 and there are no access problems for me.

- thanks for your help

**Comment by guygastineau** [comment] 2018-07-19 18:47
Maybe. I can access that from within the site, but following the link you post gives me a 500 error

**Comment by hgvanpariya** [comment] 2018-07-19 18:47
@NobbZ : I'm trying to join Bash first time...

**Comment by iHiD** [comment] 2018-07-20 08:51
This should now be fixed via [this commit](https://github.com/exercism/website-copy/commit/85026db71a8723ddfb18771c897816296e49389e).

**Comment by guygastineau** [comment] 2018-07-20 12:36
@hgvanpariya could you verify if you can access the bash track so this can be closed please :smile:

**Comment by hgvanpariya** [comment] 2018-07-20 13:11
@guygastineau : yes, now I'm able to access it, Thank you . Please close this issue.

**Closed** 2018-07-20 13:13 UTC
Labels: status/fixed
