### ISSUE TITLE
Use my timezone

### ISSUE THREAD

**Issue by zenspider** [exercism/exercism.io#1616] opened 2014-06-28 00:28 UTC
Nit Stats page shows a chart of nits over time. But the time is GMT or something odder (seems to flip at 5pm pacific). It'd be preferable if it showed the numbers shifted to my timezone. As it currently stands, half the work I did today show up yesterday.

**Comment by mhelmetag** [comment] 2016-03-08 19:15
From what I can see, exercism is saving most timestamps in utc. It would be cool to look into a JS hook to update these times with the correct timezone. It also might just be easier to add a column for the user to set their timezone and then, in the presenters, convert the times to the user's timezone.

**Comment by kytrinyx** [comment] 2016-03-09 15:52
Yeah, either of these would be fine.

**Comment by nathanbwright** [comment] 2016-07-14 15:07
Is this still active?

I got the dev environment running locally, assumed a user, and then went to http://localhost:4567/notifications 

For some reason all the notifications show the track icon but no message.

I don't know if I'm just missing something obvious.

![exercism](https://cloud.githubusercontent.com/assets/4740018/16844300/de0e1774-49a1-11e6-97b3-abbd9e633455.png)

**Comment by kytrinyx** [comment] 2016-07-15 21:18
Yeah, the issue is still active. The seed data is probably missing something vital :/ I doubt that you're missing anything, it's supposed to be super simple (so sorry that it isn't!).

**Comment by nathanbwright** [comment] 2016-07-15 21:57
@kytrinyx - Thanks for getting back with me! Don't bother looking into it yet... I'm working out how everything is setup. I'll ping you again if I hit a roadblock.

**Comment by kytrinyx** [comment] 2016-07-15 22:01
OK, cool!

**Comment by nathanbwright** [comment] 2016-07-29 17:47
@kytrinyx  - Ok, I think I have a JS solution for this. I don't know exactly where to put it though... Do I just put it into `frontend/app/js/script.js`?

**Comment by kytrinyx** [comment] 2016-07-29 17:54
The frontend setup is described in https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#frontend-development-setup but I just realized that it's a little bit unspecific.

The short answer is yes, that will work. I think. :)

**Comment by Insti** [comment] 2016-07-29 18:18
@nathanbwright My dev notifications page also looks like that, so if you have a fix I'd be happy to know what it is!

**Comment by kytrinyx** [comment] 2016-07-29 19:46
@Insti That's my fault. The [seed data](https://github.com/exercism/seeds) hasn't been updated to handle the data needed on the dashboard.

**Comment by nathanbwright** [comment] 2016-07-29 22:15
@Insti - Run `bundle exec rake dev:seed:notifications username=alice` to get regular looking notifications for `alice`

**Comment by nathanbwright** [comment] 2016-07-29 22:16
@kytrinyx - I developed in Chrome/Safari and everything was working fine... Then I decided to check in IE and guess what? IE deals with dates differently. Who would have known? 👿 

What's the lowest version of IE that needs to be supported?

**Comment by kytrinyx** [comment] 2016-07-30 02:16
> What's the lowest version of IE that needs to be supported?

We've been pretty lax about checking things in IE, but the current thinking is to support whatever Microsoft still supports. On the other hand... if it doesn't work but doesn't feel broken, I'd be OK with starting with this and doing a second pass to try to fix IE (since this would improve the experience for a bunch of people).

**Comment by nathanbwright** [comment] 2016-08-01 14:28
@kytrinyx - I don't know if I did the pull request correctly. I haven't done this before...  If I missed something please let me know and I'll fix it.

**Comment by kytrinyx** [comment] 2016-08-01 16:39
> If I missed something please let me know and I'll fix it.

Thank you :heart: -- you got it right, we'll help figure out the details over in the pull request.

**Comment by kytrinyx** [comment] 2016-08-13 16:06
I'm deploying the fix for this now. Thanks so much, @nathanbwright!

**Closed by kytrinyx** 2016-08-13 16:06 UTC
Labels: good first patch
