### ISSUE TITLE
Clicking "Read more" on submissions/nitpick page doesn't go to help (Firefox)

### ISSUE THREAD

**Issue by voltagex** [exercism/exercism.io#2298] opened 2015-04-03 04:50 UTC
e.g. http://exercism.io/submissions/0e98edca44044d6c8899694603be4a81

1. Go to a page with the blue feedback guide box
2. Click "read more"
3. Textbox opens

Expected: help opens in a new tab.

![readmore](https://cloud.githubusercontent.com/assets/159567/6978169/ea484270-da18-11e4-877f-c2b380385ea5.gif)

**Comment by trueheart78** [comment] 2015-04-03 14:41
Clicking anywhere in the blue box on FireFox closes the box. Also acts in this manner on Chrome.

Removed the `data-dismiss="alert"` from the div with id of `feedback_guide_alert` and everything works.

**Comment by kytrinyx** [comment] 2015-04-03 16:37
Can you still dismiss it with the little `x` if you remove that?

**Comment by mtakac** [comment] 2015-04-03 17:00
> Can you still dismiss it with the little x if you remove that?

I don't think so. Anyway I wouldn't go into too much trouble fixing this now: One of the first things we should do regarding new front end is change bootstrap javascript plugins for angular ui bootstrap (a rewrite of bootstrap into angular) and that will solve this issue.

**Comment by trueheart78** [comment] 2015-04-03 17:12
@kytrinyx Yes, the `x` still works - it also has that dismiss-alert attribute. The problem is the parent div does, as well.

**Comment by kytrinyx** [comment] 2015-04-03 17:15
Got it. Sweet!

**Comment by bartj3** [comment] 2015-04-07 14:17
I would like to create a fix for this, am I correct in assuming that only the `x` should close the alert?

At the moment the closing by clicking the alert is different then actually clicking the x.
Clicking the alert itself will close it, but it will be open again after a reload. Clicking the `x` will set a cookie `feedback_guide_alert` so the guide won't show again.

**Comment by kytrinyx** [comment] 2015-04-08 01:56
Thanks! Yeah, only the x should close the alert.

**Closed** 2015-04-08 13:38 UTC
Labels: bug, good first patch
