### ISSUE TITLE
Discussion forum to get guidance without answer

### ISSUE THREAD

**Issue by monkbroc** [exercism/exercism.io#2276] opened 2015-03-30 18:59 UTC
This is a suggestion/feature request from [jemagee](http://exercism.io/jemagee).

> I appreciate the guidance (and some sort of discussion forum without answers where people can get guidance when they are stuck would be incredibly awesome. You can't really get help until after you've submitted an answer but at that point you can see everyone else's answers)

**Comment by tejasbubane** [comment] 2015-03-30 19:10
The [submitting exercises](http://help.exercism.io/submitting-exercises.html) section says that `If you get stuck, you can even submit an unfinished solution`. So users can submit whatever they can do and then ask questions in comments as to where they are stuck and what are the problems they are facing.

A separate discussion forum is not required for this IMO. This will also keep all the discussion related to a particular problem at one place.

**Comment by monkbroc** [comment] 2015-03-30 19:12
I agree. But I wanted to put this out that maybe it's not obvious enough that it's possible to submit an unfinished exercise.

**Comment by tejasbubane** [comment] 2015-03-30 19:38
@monkbroc Good that you brought it up. This had come up in #2015 and I thought the [submitting exercises](http://help.exercism.io/submitting-exercises.html) section was a good place for this (https://github.com/exercism/docs/pull/122). Looks like that is not so obvious. Can you think of a better place to put it?

**Comment by mtakac** [comment] 2015-03-30 23:40
Having the copy in submitting exercises section is fine but IMO not enough. What about the README file?  Anyway even then it is not ideal. You submit the incomplete exercise so you can ask for help, but you need to wait for the answer and that could be quite annoying. Some kind of "global" discussion for each exercise would still be helpful.

On the other hand you can see other solutions after submitting. I assume the problem here is that you don't want to see the complete solution, you want to get just a hint. This would probably be problematic even with the discussion forum (users posting solutions instead of hints). I think the best way to go would be to introduce some hints in the UI on the exercise page: There would be a copy in README, saying that you can get some hints after submitting, and there would be some basic tips hidden on the submission page that would show up after a click.

**Comment by monkbroc** [comment] 2015-03-31 00:41
Or how about `exercism hint` from the command line? People that nitpicked a
problem enough could be offered to write hints that would delivered by the
above command. Think of those hints as pre-emptive nitpicks.

**Comment by kytrinyx** [comment] 2015-03-31 01:36
I like the idea of hints (pre-emptive nitpicks). This might not always be possible, since some exercises can be tackled in many different ways, but I'd be very, very curious to see where people are stuck so that we can figure out what kind of hints would be helpful.

I wonder how we could collect the "stuck" cases for research purposes.

**Comment by monkbroc** [comment] 2015-03-31 01:50
Here's how it could work:

Add a line to the bottom of each README that says "If you're stuck, type `exercism hint`. You can also submit your partial solution to get some feedback"

`exercism hint` prints a random 1-2 line hint like "Try `String#scan` http://ruby-doc.org/core-2.2.0/String.html#method-i-scan"

In the backend, if a user has given 10 nitpicks to a problem, send them a notification to write some hints for the problem. I'd leave it open for anybody that submitted a solution to write hints, but only prompt people that saw a lot of solutions to go do it.

**Comment by kytrinyx** [comment] 2015-03-31 02:33
I think this could be really useful. If we don't have any hints for something we could respond with a friendly apology and a suggestion that they submit it and ask for some help.

**Comment by jwood803** [comment] 2015-03-31 02:40
I like the idea as well. It's always nice to know there's an extra place to go for some help.

**Comment by tejasbubane** [comment] 2015-03-31 05:58
I like this idea of hints. :+1:

**Comment by kytrinyx** [comment] 2015-04-04 05:45
In the past two weeks I have done a fairly large audit of the issues on exercism, and realised that there are a handful of recurring topics that come up, and many issues are trying to address the same underlying topic. Rather than trying to address each issue individually, I believe that it will be useful to collect the suggestions in one place, as well as discuss the underlying problems that have prompted these issues.

I am creating summary topics for these recurring issues, and closing the associated discussions that prompted the issue. If I have missed some important points in the summary, please add your voice to the discussion there.

-------

Summary topic for feedback that doesn't fall under the banner of peer code review: #2312.

**Closed by kytrinyx** 2015-04-04 05:45 UTC
Labels: audit/wish, copy fix, topic: automated feedback, topic: critique quality, ux

**Comment by muritz** [comment] 2022-01-06 22:02
Hey there all of you,
I am new to exercism and I really need some help. 
I am stuck with the grains.py. All solutions I tried work fine on my Mac, but don't pass the exception raised tests online. However I cannot contact any mentor, nor can I submit the unfinished solution. After spending several hours, I think I could really use some help.

Is there anyone who can help? Or at least if someone could tell me how to receive mentoring .....

Thank you sooooo much for your help.

**Comment by kotp** [comment] 2022-01-07 02:52
@muritz If you submit your solution using the command line tool `exercism submit grains.py` after having downloaded the exercise, you can request a mentor.  If you are trying to submit the exercise via the web editor, it will not allow a request (last I checked, and confirmed by what you are indicating here) to be mentored.

**Comment by muritz** [comment] 2022-01-07 10:34
@kotp Thank you Victor, I have figured out everything and I'm still going with a mentor who is very helpful.
I'm not looking for shortcuts. 
My solutions all worked except I didn't understand that the test routines are searching for exact spelling of an exception. 😂
My ambition is to get around solving on my own. Didn't spend a look into community solutions.

Stay as kind as you are .... greetings from Germany 🇩🇪 Muritz
