### ISSUE TITLE
Lost account progress by changing github account name

### ISSUE THREAD

**Issue by liarokapisv** [exercism/exercism.io#3242] opened 2016-11-11 00:15 UTC
After I changing my github username (or merged accounts, I am not 100% sure) a few months ago (from Demon-In-A-Jar), I lost all of my progress. I found a few relevant issues and so I am not sure if this has been fixed. Is there some way to retrieve the lost progress?

**Comment by esparta** [comment] 2016-11-11 06:52
This looks like a duplicate of #3100

**Comment by kytrinyx** [comment] 2016-11-12 21:57
@liarokapisv changing the GitHub username shouldn't lose your progress, unless you create a new account. When logging in we look at the GitHub ID not the username, and use that to update the username that is shown on Exercism.

Your Demon-In-A-Jar user still exists: http://exercism.io/Demon-In-A-Jar

The GitHub user id for these two users is different in the database.

**Comment by liarokapisv** [comment] 2016-11-13 13:26
It appears that I deleted the github account and associated my original email with my current one and now I can't access my original exercism user account. It's been a while so I didn't remember. This is getting offtopic, but is it possible to merge the two accounts or associate the exercises with my current account?

**Comment by kytrinyx** [comment] 2016-11-25 20:50
Yeah, we should be able to do that manually, if the email is the same on both. I'll look into it.

**Comment by kytrinyx** [comment] 2016-11-28 19:25
@liarokapisv I don't have an email address on either account, so I have no way of verifying that these are both owned by you. That said, since Demon-In-A-Jar no longer exists on GitHub, I'll go ahead and merge them. I need to write a script to do it, and will report back when it's done.

**Comment by kytrinyx** [comment] 2016-11-28 20:53
Note: Where there are duplicates, the submissions and conversations will be simply attached to the new account, even if the code is identical.

**Closed** 2016-11-30 00:16 UTC
Labels: support

**Comment by kytrinyx** [comment] 2016-11-30 00:25
@liarokapisv Your accounts should now be merged. Please let me know if something doesn't look right.
