### ISSUE TITLE
Prior to the new site there were teams

### ISSUE THREAD

**Issue by barnzdan** [exercism/exercism.io#4195] opened 2018-08-07 12:38 UTC
It seems that teams were removed after moving to the new site. This was a feature that was quite beneficial to our dev team. Were these removed for a reason?

**Comment by iHiD** [comment] 2018-08-07 12:40
Duplicate of https://github.com/exercism/exercism.io/issues/3815 Your question is answered there :)

**Closed by iHiD** 2018-08-07 12:40 UTC
