### ISSUE TITLE
Create an achievement system to gamify exercism

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1978] opened 2014-10-20 02:42 UTC
See [video game achievements](http://en.wikipedia.org/wiki/Achievement_(video_gaming)) for an explanation of the basic idea.

Achievements would be displayed in detail on your personal profile and some sort of smaller graphic next to your name when you nitpick or other people see your submission.

Some obvious achievements:
* First problem submission
* First review
* First problem submission for a particular language track
* First review for a particular language track
* First improvement to exercism (pull request via github)

Given that the above list pretty much covers all the activities that you can do on exercism, I would extend the list by extending it by orders of magnitude:

* Tenth problem submission
* Tenth review
* Tenth problem submission for a language
* Tenth review for a langauge
* Tenth improvement to exercism (pull request via github)

Where to go next is a matter of how difficult you want to make it to level up in the achievement system.  Typical progressions go something like this:

1, 10, 25, 50, 100, 250, 500

The point is to give positive reinforcement initially without much effort and thereafter only with increasing effort.

If we were to adopt this system, then I would suggest something sexier than the text I've written above for the achievements :smile:.  There are basically only a few activities we want to recognize with an achievement:
* working problems
* giving feedback
* trying languages
* contributing to exercism itself

For each of these, we want to measure the amount of participation and aware achievements for more and more participation.  You can think of the progression within each activity as achieving another "rank" and you can give the ranks different titles (this is sexier than just the number of X performed), with rank titles themed to each kind of activity.

| Number of Reviews | Title |
|-------|--------|
| 1 | Commenter |
| 10 | Nit Picker |
| 25 | Reviewer |
| 50 | ? |
| 100 | ? |
| 250 | Editor |
| 500 | Editori in Chief |

There's lots of room for brainstorming here.

Thankfully, implementing this on the site is fairly easy.  The hard part is coming up with cool graphics and achievement names for each activity.

**Comment by kytrinyx** [comment] 2016-10-23 23:48
I'm going to go ahead and close this, since I really don't want to go down the path of gamification. I do think that there's a lot that we can do in order to improve the quantity and quality of the feedback, and have opened an issue here to explore that at a higher level: https://github.com/exercism/discussions/issues/88

**Closed by kytrinyx** 2016-10-23 23:48 UTC

**Comment by da9l** [comment] 2018-12-09 14:44
Given the change to mentorship instead of a badge system have you measured the amount of comments, likes and thumbsups solutions has been given. I'm getting the impression that non-mentors has almost stopped writing any comments at all and the number of newly created solutions has decreased. 

I think a badge system like the one on stackoverflow would make more non-mentors comment and give feedback on non-track exercises and therefore shorten the feedback loops.

**Comment by NobbZ** [comment] 2018-12-09 15:11
> I'm getting the impression that non-mentors has almost stopped writing any comments

Not “almost”. Non-mentors are currently unable to comment on solutions.

> the number of newly created solutions has decreased. (I'm on the fsharp track)

Not every one publishes a new solution. But I have no statistics about how many submissions there were before v2, nor do I have how many there are today.

**Comment by da9l** [comment] 2018-12-09 19:58
I stand corrected. I see that now. No wonder the amount of comments has plummeted :-p
Is it possible to get submission, likes and comment statistics from the site?

**Comment by iHiD** [comment] 2018-12-09 20:17
The amount of solutions and comments have dramatically increased since
launch of v2. They're just private mentoring conversations now so you're
not seeing them publicly.

**Comment by iHiD** [comment] 2018-12-09 20:36
I'm not sure about f#. I'll ping the mentors to look :) The issue is the shear volume of solutions generally (around 10,000 last week). Some tracks keep up, others need more mentors.
