### ISSUE TITLE
Add exercise to track is not properly unlocked

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism.io#4080] opened 2018-07-27 03:03 UTC
@iHiD or @kytrinyx 

This was an issue recently that I thought was resolved when another exercise that I had added to Delphi was locked was later unlocked...

![image](https://user-images.githubusercontent.com/6978003/43299255-8859fac6-9127-11e8-9e1d-ee2f28e26649.png)
The exercise that I have indicated in the image appears to be unlocked.  If I click the glyph I am just taken back to the main page for the track.  If it is locked I probably shouldn't be able to click it.  Seeings how it isn't a core exercise all the icons beneath the core are probably all expected to be clickable since the core exercise is completed.

Down at the bottom of the list of available exercises it does appear locked.
![image](https://user-images.githubusercontent.com/6978003/43299353-e0e53340-9127-11e8-8f4e-09b94f0107a5.png)

If this is still an open issue, then please ignore more me.  Otherwise I appear to still be seeing the same problem.  New exercises are locked for students where they shouldn't be.

**Comment by rpottsoh** [comment] 2018-07-27 03:10
This is probably the same as #3867.  Please close if you feel that it is,

**Comment by iHiD** [comment] 2018-07-27 10:37
Yeah - probably a duplicate of #3867 if that exercise is new. Is it?

**Comment by rpottsoh** [comment] 2018-07-27 11:44
Yes it is new.  I couldn't be sure if issue was new or not as previous new exercise that was locked is now unlocked. 


Sent from my android device.

**Comment by rpottsoh** [comment] 2018-07-27 14:20
The new, locked, exercise is a child of Leap.  When I click on Leap I am informed that `This solution has been imported from independent mode. Mentoring will become available when your other solutions have been mentored.`  Which other solutions?  The other exercise, that was previously locked, is a child of hello-world, which auto unlocks...  Will the latest new exercise (the child of Leap) unlock once my Leap solution is mentored?

It feels like the child exercises end up in a sort of limbo state when added .  Or they appear to be where they are listed beneath their parent core exercise.  The imported, completed exercise , is both alive and dead...

I have added a comment to my Leap submission asking that the other track mentor "mentor" my submission.  Will that unlock the presently locked exercise?....

**Comment by iHiD** [comment] 2018-07-27 14:56
Yeah. This just needs #3867 fixing. The reason it worked before is that I wrote a big script to fix unlocking after ETL which had the site effect of fixing this as a one off. Mind closing as duplicate and mentioning it in the other issue so I don't forget the extra stuff you've written here pls?

**Comment by rpottsoh** [comment] 2018-07-27 15:59
closed in favor of #3867

**Closed** 2018-07-27 15:58 UTC
