### ISSUE TITLE
[java] unchanged: 0, updated: 0, new: 0

### ISSUE THREAD

**Issue by pigg3h** [exercism/exercism.io#2851] opened 2016-04-28 07:46 UTC
When I type exercism fetch java it returns "unchanged: 0, updated: 0, new: 0", tried everything on the support page to no avail. Not really sure where else to go...

**** Debug Information ****
Exercism CLI Version: 2.2.5
Exercism CLI Latest Release: 2.2.5
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\Richard
Config file: C:\Users\Richard\.exercism.json
API Key: matches api in account
Exercises Directory: C:\Program Files\exercism
Testing API endpoints reachability
	* API: http://exercism.io [connected] 132.9709ms
	* GitHub API: https://api.github.com/ [connected] 371.4997ms
	* XAPI: http://x.exercism.io [connected] 430.2009ms

**Comment by pigg3h** [comment] 2016-04-29 05:07
I figured it out and feel dumb haha. Didn't realize you had to call a specific exercise.

**Comment by tejasbubane** [comment] 2016-04-29 12:08
If I am not wrong, `exercism fetch java` will fetch the next available exercise if any and if none is available, it will tell `0 fetched`. I think we should mention this somewhere in the docs. 

I just noticed that the [cli guide](http://exercism.io/cli) does not say anything about the usage. Is there any other place where this is described?

**Comment by kytrinyx** [comment] 2016-04-29 18:33
Probably not. We've been moving documentation around, and I wouldn't be surprised if we simply missed this.

**Comment by kytrinyx** [comment] 2016-04-30 15:32
> I figured it out and feel dumb haha. Didn't realize you had to call a specific exercise.

OK, this is actually a bug. I tried this and if you haven't started a track yet, it doesn't deliver the exercise. Super frustrating, and we should absolutely figure out how to fix it quickly.

I think the problem is in the x-api, and have posted an issue there: https://github.com/exercism/x-api/issues/106

I'm going to close this in favor of the x-api issue.

**Closed by kytrinyx** 2016-04-30 15:32 UTC

**Comment by kytrinyx** [comment] 2016-05-01 17:15
This should be fixed in production.
