### ISSUE TITLE
"Couldn't find that user" error when clicking on the Activity Stream

### ISSUE THREAD

**Issue by horatius83** [exercism/exercism.io#2880] opened 2016-05-13 00:01 UTC
I get the error "Couldn't find that user" when clicking on the Activity Stream. I also recently submitted a solution and the language isn't showing up (It's blank instead of Haskell)

**Comment by kytrinyx** [comment] 2016-05-14 16:29
@horatius83 thanks for reporting this.

What does the output of `exercism debug` say?

**Comment by horatius83** [comment] 2016-05-18 21:43
I should add that the job I submitted was with a very old client (about a year old). I'll get the debug info, but I've updated the client since then so I don't know how useful that will be.

**Comment by kytrinyx** [comment] 2016-05-22 05:25
Yeah, that's a good point. I wonder if the right thing to do here is to start asking people to upgrade if we receive a call to an old client. We'd have to do some testing to see if old clients would even print error messages—it's a bit of a messy history.

**Comment by horatius83** [comment] 2016-05-27 00:14
**** Debug Information ****
Exercism CLI Version: 2.2.5
Exercism CLI Latest Release: 2.2.5
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\Tyler Durden
Config file: C:\Users\Tyler Durden\.exercism.json
API Key: <redacted> 
Exercises Directory: C:\exercism
Testing API endpoints reachability
        * API: http://exercism.io [connected] 183.0288ms
        * XAPI: http://x.exercism.io [connected] 238.6649ms
        * GitHub API: https://api.github.com/ [connected] 271.7551ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please includ
e this information (except your API key. Keep that private).

**Comment by horatius83** [comment] 2016-05-27 00:15
Like I said before, I submitted and attempted to fetch with the old client, and now, even with the new client I can't seem to get new exercises. (This debug output is from the new client)

**Comment by kytrinyx** [comment] 2016-05-27 16:14
OK, thanks for the details. I'm looking into this.

**Comment by kytrinyx** [comment] 2016-05-27 16:30
@horatius83 Can you confirm the reproduction steps for me? From the issue here it sounds like you're experiencing several different (but probably related) problems.

The first is that you are unable to view the activity streams.

1. log in to exercism.io
1. click on Activity Streams in the top menu
1. you receive the error message "Couldn't find that user"

What URL are you on when you get that error message?

Do you get this error message if you visit the following urls?

- http://exercism.io/tracks/haskell/exercises
- http://exercism.io/tracks/python/exercises
- http://exercism.io/tracks/go/exercises

> I also recently submitted a solution and the language isn't showing up (It's blank instead of Haskell)

I cleaned up some data last week (I've been trying to figure out how the old client submission is misunderstood on the backend, but I'm not sure which client version we're talking about, and am unable to reproduce the issue locally). Are you still missing the language on your submission?

> even with the new client I can't seem to get new exercises

To be clear, if you say `exercism fetch haskell` it doesn't fetch any new exercises for you? What is the output after running the command?

**Comment by horatius83** [comment] 2016-05-28 19:01
I don't know what changed, but it seems to be working fine now.

**Comment by kytrinyx** [comment] 2016-05-28 19:04
OK, great! I'm going to close this, but please don't hesitate to re-open it or open a new one if you experience similar issues.

**Closed by kytrinyx** 2016-05-28 19:04 UTC
Labels: bug?
