### ISSUE TITLE
Unable to fetch exercises

### ISSUE THREAD

**Issue by Guwanjith** [exercism/exercism.io#1906] opened 2014-09-29 03:40 UTC
I just installed exercism - I think I installed it correctly. However, I am unable to fetch new exercises. I still have not fetched a single exercise. When I try to fetch new exercises, I get the following error message:

 mkdir /path: permission denied

Let me know how I should go about fixing this.

Thanks,

Guwanjith

**Comment by guru-teja** [comment] 2017-02-17 13:17
$ exercism fetch swift
2017/02/17 18:44:06 Get http://x.exercism.io/v2/exercises/swift?key=MY_API_KEY : EOF
I am getting this after configuring the key and path.
How to open an exercise? and where to enter the solution code

**Comment by kytrinyx** [comment] 2017-02-20 17:16
@guru-teja please run the command `exercism debug` and paste the output here.

**Comment by guru-teja** [comment] 2017-02-21 05:41
@kytrinyx  here is the output you asked for 

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/Ganesh
Config file: /Users/Ganesh/.exercism.json
API Key: /*MY_API_KEY*/
Exercises Directory: /Users/Ganesh/Users/Ganesh/MyEx
Testing API endpoints reachability
	* XAPI: http://x.exercism.io [Get http://x.exercism.io: EOF] 822.244458ms
	* API: http://exercism.io [Get http://exercism.io: EOF] 1.318212594s
	* GitHub API: https://api.github.com/ [connected] 1.544939383s

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

**Comment by kotp** [comment] 2017-02-21 06:32
Why the double reference to `Users/Ganesh` for "Exercises Directory"?  Does that really exist?  If not, please modify your `/Users/Ganesh/.exercism.json` file to reflect the correct folder.

**Comment by guru-teja** [comment] 2017-02-21 07:03
@kotp I have uninstalled and reinstalled exercism, since I got the problem


**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/Ganesh
Config file: /Users/Ganesh/.exercism.json
API Key: MY_API_KEY
Exercises Directory: /Users/Ganesh/exercism
Testing API endpoints reachability
	* XAPI: http://x.exercism.io [Get http://x.exercism.io: EOF] 700.842108ms
	* API: http://exercism.io [Get http://exercism.io: EOF] 972.619449ms
	* GitHub API: https://api.github.com/ [connected] 1.362277102s

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

but still getting the same when "exercism fetch swift" is performed

2017/02/21 12:30:38 Get http://x.exercism.io/v2/exercises/swift?key=MY_API_KEY: EOF

**Comment by kotp** [comment] 2017-02-21 07:14
Did you click on the link to get your api key?

**Comment by kotp** [comment] 2017-02-21 07:15
I am having to assume that you removed the real API key and placed in "MY_API_KEY" as a holder.

**Comment by guru-teja** [comment] 2017-02-21 07:21
Yes i had my API key since I am asked not to share it, I changed the key to "MY_API_KEY"

**Comment by guru-teja** [comment] 2017-02-21 07:23
All I need to know is how to open an exercise and submit the solution as I having the trouble doing it.

**Comment by kotp** [comment] 2017-02-21 07:37
Yes.  Of course.

So when you run the command to fetch, you are in your exercism folder... indicated similar to below?

```[swift] pwd                                                                                                                    
/home/victor/exercism/swift
[swift] exercism fetch swift                                                                                                   2:36:35 

Not Submitted: 1 problem
swift (Leap) /home/victor/exercism/swift/leap

unchanged: 1, updated: 0, new: 0

```

**Comment by kotp** [comment] 2017-02-21 07:38
You can come to [chat in support](https://gitter.im/exercism/support) since it looks like we can work on this together synchronously, if you would like.

**Comment by kytrinyx** [comment] 2017-02-21 16:38
Thanks @kotp ✨ (always!) for helping out both here and in the support chat.

> Exercises Directory: /Users/Ganesh/Users/Ganesh/MyEx

I think the problem is your configuration (which lives in `/Users/Ganesh/.exercism.json`).

You can look at the current configuration values by running: `exercism configure`. It will show something like this:

```
Configuration written to /Users/Ganesh/.exercism.json

  --key=***redacted***
  --dir=/Users/Ganesh/Users/Ganesh/MyEx
  --host=http://exercism.io
  --api=http://x.exercism.io
```

Then you can update the value that you need to fix by running:

```
exercism configure  --dir=/Users/Ganesh/MyEx
```

**Comment by guru-teja** [comment] 2017-02-22 09:33
I still dont get it, even after changing the directory @kytrinyx , so I reinstalled it. here is my output

Ganesh$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/Ganesh
Config file: /Users/Ganesh/.exercism.json
API Key: ***redacted***
Exercises Directory: /Users/Ganesh
Testing API endpoints reachability
	* API: http://exercism.io [Get http://exercism.io: EOF] 387.711136ms
	* XAPI: http://x.exercism.io [Get http://x.exercism.io: EOF] 1.057187608s
	* GitHub API: https://api.github.com/ [connected] 1.555430555s

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).


Ganesh$ exercism fetch swift
2017/02/22 15:00:58 Get http://x.exercism.io/v2/exercises/swift?key=***redacted***: EOF


Is there any GUI version or easy tutorial for newbies??

**Comment by kotp** [comment] 2017-02-22 10:23
Does your folder look like this?

```
hello-world
├── helloWorld.swift
├── helloWorldTest
│   ├── helloWorldTest.swift
│   └── Info.plist
├── helloWorld.xcodeproj
│   ├── project.pbxproj
│   ├── project.xcworkspace
│   │   └── contents.xcworkspacedata
│   └── xcshareddata
│       └── xcschemes
│           └── helloWorldTest.xcscheme
└── README.md

```

**Comment by kotp** [comment] 2017-02-22 10:28
Hmm... noticed something strange with the `Build OS/Architecture` line.  I am not on OSX though, can someone confirm this is normal to have nothing show for this line?

**Comment by tejasbubane** [comment] 2017-02-22 10:49
@kotp This is my output on OSX:

```
exercism version 2.3.0

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/tejas
Config file: /Users/tejas/.exercism.json
API Key: ******
Exercises Directory: /Users/tejas/exercism_submissions
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 433.085027ms
	* XAPI: http://x.exercism.io [connected] 588.321494ms
	* API: http://exercism.io [connected] 623.472845ms
```

**Comment by guru-teja** [comment] 2017-02-22 11:47
No, I dont have a hello-world folder at all @kotp 

And I am using MAC OS X 10.9 in VM ware on windows 7.

**Comment by kotp** [comment] 2017-02-22 11:59
@guru-teja does the exercism tools work for you on your native operating system?

It "should work" in a virtual machine.  But it is another layer to deal with.

**Comment by kotp** [comment] 2017-02-22 12:03
The `EOF` part of the two lines and the information that you are using a virtual machine on windows, tells me that the line endings that are not compatible on your file system may be causing the problem, and the operating system, maybe causing the problem.

**Comment by guru-teja** [comment] 2017-02-22 12:16
Ok, Thank you. I will try with my native operating system.

**Comment by kytrinyx** [comment] 2017-02-22 15:57
> Is there any GUI version or easy tutorial for newbies?

Yes, there is a GUI: https://github.com/exercism/gui

**Comment by kytrinyx** [comment] 2017-03-27 17:52
I am going to close this. If you run into problems fetching, please open a new issue.

**Closed by kytrinyx** 2017-03-27 17:52 UTC
Labels: support
