### ISSUE TITLE
Solutions approved without comment do not change status properly

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3978] opened 2018-07-17 22:23 UTC
When I go to my mentor dashboard I am currently seeing four solutions under the "Solutions you're mentoring" heading.

Three of these are solutions that I approved without a comment.

**Comment by NobbZ** [comment] 2018-07-17 22:48
Which filter exactly?

Is it requires action from you? If so has the student iterated since you approved?

If you answered yes, it's probably a duplicate of #3880.

**Comment by junedev** [comment] 2018-07-19 19:48
I just noticed that leaving a comment makes the entries disappear from the dashboard.

**Closed** 2018-07-23 15:05 UTC
Labels: area/mentor-tools, priority/high, type/bug
